//! Prebuilt Eo9 guest components, bundled as plain data.
//!
//! The `eo9` binary embeds whatever `cargo xtask build-guest` produced when it was built
//! inside the repository; a build without that directory (most importantly
//! `cargo install eo9` from crates.io) falls back to the set bundled here, so a fresh
//! install still seeds a working shell, the examples, the coreutils, and the standard
//! stub providers.
//!
//! `data/index.rs` and the `data/*.wasm` files are generated by
//! `cargo xtask refresh-components` from `guest/target/components/` and verified against
//! a fresh guest build by `cargo xtask package`; they are never edited by hand.

// `BUNDLED_COMPONENTS: &[(&str, &[u8])]` — (file stem, component bytes), sorted by stem.
include!(concat!(env!("CARGO_MANIFEST_DIR"), "/data/index.rs"));

/// The bundled component set as `(file stem, bytes)` pairs (e.g. `("eosh", …)`),
/// sorted by stem. Stems match the file names `cargo xtask build-guest` produces under
/// `guest/target/components/`.
pub fn bundled() -> &'static [(&'static str, &'static [u8])] {
    BUNDLED_COMPONENTS
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_bundle_is_present_sorted_and_non_empty() {
        let set = bundled();
        assert!(
            !set.is_empty(),
            "the bundled component set is empty — run `cargo xtask refresh-components`"
        );
        assert!(set.iter().any(|(stem, _)| *stem == "eosh"));
        for pair in set.windows(2) {
            assert!(pair[0].0 < pair[1].0, "bundle index is not sorted");
        }
        for (stem, bytes) in set {
            assert!(!bytes.is_empty(), "bundled component {stem:?} is empty");
            assert!(
                bytes.starts_with(b"\0asm"),
                "bundled component {stem:?} does not look like a wasm binary"
            );
        }
    }
}
