//! Test fixtures: tiny components built in-process from WIT text.
//!
//! Each fixture is generated by parsing WIT into a fresh `Resolve`, producing a dummy
//! core module for the selected world (`wit-component`'s `dummy-module` feature), and
//! wrapping it into a component. Bodies are never executed -- the algebra is math on
//! types and wiring -- so dummy implementations are exactly enough.
//!
//! The `fix:kit` package is a self-contained vocabulary exercising every shape the
//! algebra cares about; the `fix:hello` fixtures use the real `eo9:*` packages from
//! `wit/` so the crate is also tested against the repository's actual interface
//! vocabulary.

use std::path::PathBuf;

use eo9_component::Component;
use wit_component::{ComponentEncoder, StringEncoding, dummy_module, embed_component_metadata};
use wit_parser::{LiftLowerAbi, ManglingAndAbi, Resolve};

/// The self-contained fixture vocabulary.
const KIT_WIT: &str = r#"
package fix:kit@1.0.0;

/// Types-only interface: carries no authority (mirrors the eo9:*/types pattern).
interface types-a {
    resource gadget;
}

interface cap-a {
    use types-a.{gadget};
    make: func() -> gadget;
    ping: func(g: borrow<gadget>) -> u32;
}

/// The mechanically derived optional flavor of cap-a.
interface cap-a-optional {
    use types-a.{gadget};
    default: func() -> option<gadget>;
}

interface cap-b {
    pong: func() -> u64;
}

interface cap-c {
    zap: func(level: u32) -> string;
}

/// A binary requiring cap-a and cap-b.
world app {
    import cap-a;
    import cap-b;
    export main: func(input: string, count: u32) -> result<string, string>;
}

/// A binary requiring only cap-a.
world app-a {
    import cap-a;
    export main: func() -> result<_, string>;
}

/// A binary requiring cap-b and optionally using cap-a.
world app-optional {
    import cap-b;
    import cap-a-optional;
    export main: func(verbose: bool) -> result<string, string>;
}

/// A binary asking for two instances of cap-a under distinct slot names.
world named-slots {
    import left: cap-a;
    import right: cap-a;
    export main: func() -> result<_, string>;
}

/// A configurable provider of cap-a.
world provider-a {
    export cap-a;
    export configure: func(seed: u64) -> result<_, string>;
}

/// A provider of both cap-a and cap-b.
world provider-ab {
    export cap-a;
    export cap-b;
}

/// Middleware: provides cap-b, needs cap-a.
world provider-b-from-a {
    import cap-a;
    export cap-b;
}

/// Middleware: provides cap-c, needs cap-b.
world provider-c-from-b {
    import cap-b;
    export cap-c;
}

/// The cap-a.none stub: exports the optional flavor (answering none when run).
world provider-none-a {
    export cap-a-optional;
}

/// The empty provider: the identity of the algebra.
world empty {
}

/// Not an Eo9 module: an unexpected function export.
world odd-exports {
    export frobnicate: func() -> u32;
}

/// Not an Eo9 module: both runnable and composable.
world both-kinds {
    export cap-b;
    export main: func() -> result<_, string>;
}
"#;

/// Same package name and slot as `fix:kit`'s cap-a, but structurally incompatible --
/// used to provoke a compose-time type mismatch.
const KIT_MISMATCHED_WIT: &str = r#"
package fix:kit@1.0.0;

interface types-a {
    resource gadget;
}

interface cap-a {
    use types-a.{gadget};
    make: func() -> gadget;
    ping: func(g: borrow<gadget>) -> string;
}

world provider-a {
    export cap-a;
}
"#;

/// Fixtures against the real `eo9:*` WIT packages in `wit/`.
const HELLO_WIT: &str = r#"
package fix:hello@0.1.0;

/// A binary requiring text output and optionally using entropy.
world hello {
    import eo9:text/text@0.1.0;
    import eo9:entropy/entropy-optional@0.1.0;
    export main: func(greeting: string) -> result<_, string>;
}

/// A stub text provider (the shape of text.null/text.capture).
world text-mock {
    export eo9:text/types@0.1.0;
    export eo9:text/text@0.1.0;
}

/// A binary requiring entropy (for composing a configured provider into).
world entropy-user {
    import eo9:entropy/entropy@0.1.0;
    export main: func(count: u32) -> result<u64, string>;
}
"#;

/// A placeholder package for fixtures that only select a world from the repository's
/// own `wit/` packages.
const EMPTY_WIT: &str = "package fix:empty@0.1.0;\n";

/// Fixture worlds against the real `eo9:time` package.
const CLOCK_WIT: &str = r#"
package fix:clock@0.1.0;

/// A binary requiring the real `eo9:time/time` capability.
world clock-user {
    import eo9:time/time@0.1.0;
    export main: func() -> result<u64, string>;
}
"#;

/// Builds a `fix:kit` fixture world and loads it.
pub fn kit(world: &str) -> Component {
    Component::load(kit_bytes(world)).expect("fixture should load")
}

/// The real `eo9:entropy/seeded` stub world (types + entropy + seeded-config), built
/// against the repository's own WIT with a dummy implementation: the same shape as the
/// real `entropy.seeded` provider in `guest/stubs`.
pub fn seeded_provider() -> Component {
    let bytes = build_bytes(
        &[("fix-hello.wit", HELLO_WIT)],
        &["text", "entropy"],
        "eo9:entropy/seeded",
    );
    Component::load(bytes).expect("fixture should load")
}

/// The real `eo9:time/frozen` stub world (types + time + frozen-config), built against
/// the repository's own WIT with a dummy implementation whose async functions are lifted
/// with the async-callback ABI: the same shape as the real `time.frozen` provider in
/// `guest/stubs`, including the async `sleep` in its API.
pub fn frozen_provider() -> Component {
    let bytes = build_bytes_with(
        &[("fix-empty.wit", EMPTY_WIT)],
        &["time"],
        "eo9:time/frozen",
        ManglingAndAbi::Legacy(LiftLowerAbi::AsyncCallback),
    );
    Component::load(bytes).expect("fixture should load")
}

/// A binary importing the real `eo9:time/time` interface (for composing a configured
/// clock provider into).
pub fn clock_user() -> Component {
    let bytes = build_bytes(&[("fix-clock.wit", CLOCK_WIT)], &["time"], "clock-user");
    Component::load(bytes).expect("fixture should load")
}

/// The real `eo9:fs/memfs` stub world, whose API interface defines its own resources --
/// the provider shape compose-time configuration cannot bind yet.
pub fn memfs_provider() -> Component {
    let bytes = build_bytes_with(
        &[("fix-empty.wit", EMPTY_WIT)],
        &["fs"],
        "eo9:fs/memfs",
        ManglingAndAbi::Legacy(LiftLowerAbi::AsyncCallback),
    );
    Component::load(bytes).expect("fixture should load")
}

/// Builds a `fix:kit` fixture world, returning raw bytes (for load-rejection tests).
pub fn kit_bytes(world: &str) -> Vec<u8> {
    build_bytes(&[("fix-kit.wit", KIT_WIT)], &[], world)
}

/// A provider exporting a structurally incompatible `fix:kit/cap-a`.
pub fn kit_mismatched() -> Component {
    let bytes = build_bytes(
        &[("fix-kit-alt.wit", KIT_MISMATCHED_WIT)],
        &[],
        "provider-a",
    );
    Component::load(bytes).expect("fixture should load")
}

/// A provider exporting `fix:ver/api` at the given package version.
pub fn ver_provider(version: &str) -> Component {
    let wit = ver_wit(version);
    let bytes = build_bytes(&[("fix-ver.wit", &wit)], &[], "provides-api");
    Component::load(bytes).expect("fixture should load")
}

/// A binary importing `fix:ver/api` at the given package version.
pub fn ver_consumer(version: &str) -> Component {
    let wit = ver_wit(version);
    let bytes = build_bytes(&[("fix-ver.wit", &wit)], &[], "needs-api");
    Component::load(bytes).expect("fixture should load")
}

fn ver_wit(version: &str) -> String {
    format!(
        r#"
package fix:ver@{version};

interface api {{
    get: func() -> u32;
}}

world needs-api {{
    import api;
    export main: func() -> result<u32, string>;
}}

world provides-api {{
    export api;
}}
"#
    )
}

/// Builds a `fix:hello` fixture world against the real `eo9:text` / `eo9:entropy`
/// packages from the repository's `wit/` directory.
pub fn eo9_fixture(world: &str) -> Component {
    let bytes = build_bytes(&[("fix-hello.wit", HELLO_WIT)], &["text", "entropy"], world);
    Component::load(bytes).expect("fixture should load")
}

/// Parses the given WIT sources (plus any `wit/<dir>` packages from the repository) and
/// encodes the selected world as a component with a dummy core implementation using the
/// synchronous ABI.
fn build_bytes(sources: &[(&str, &str)], wit_dirs: &[&str], world: &str) -> Vec<u8> {
    build_bytes_with(
        sources,
        wit_dirs,
        world,
        ManglingAndAbi::Legacy(LiftLowerAbi::Sync),
    )
}

/// [`build_bytes`], with the dummy implementation's lift/lower ABI chosen by the caller
/// (async-callback for stub-shaped fixtures whose WIT has async functions).
fn build_bytes_with(
    sources: &[(&str, &str)],
    wit_dirs: &[&str],
    world: &str,
    abi: ManglingAndAbi,
) -> Vec<u8> {
    let mut resolve = Resolve::default();
    for dir in wit_dirs {
        let path = repo_wit_dir().join(dir);
        resolve
            .push_dir(&path)
            .unwrap_or_else(|err| panic!("failed to load wit/{dir}: {err:#}"));
    }
    let mut main_package = None;
    for (path, text) in sources {
        main_package = Some(
            resolve
                .push_source(path, text)
                .unwrap_or_else(|err| panic!("failed to parse fixture WIT `{path}`: {err:#}")),
        );
    }
    let world = resolve
        .select_world(
            &[main_package.expect("at least one WIT source")],
            Some(world),
        )
        .unwrap_or_else(|err| panic!("failed to select fixture world: {err:#}"));

    let mut module = dummy_module(&resolve, world, abi);
    embed_component_metadata(&mut module, &resolve, world, StringEncoding::UTF8)
        .expect("failed to embed component metadata");
    ComponentEncoder::default()
        .validate(true)
        .module(&module)
        .expect("failed to set the fixture core module")
        .encode()
        .expect("failed to encode the fixture component")
}

/// The repository's `wit/` directory (the machine-readable interface contract).
fn repo_wit_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("..")
        .join("wit")
}
