//! The embedded component set and first-run store seeding.
//!
//! The binary carries the components `cargo xtask build-guest` had produced when it was
//! built (eosh, the examples, the standard stubs — see `build.rs`). On the first shell
//! start against an **empty** store (no name bindings at all) they are added to the
//! object store and bound under their shell names, so a freshly installed `eo9` drops
//! straight into a working shell with programs to run. Seeding never touches a store
//! that already has bindings, so user state is never clobbered and the operation is
//! idempotent; in a checkout built before `build-guest` the embedded set is empty and
//! the dev-tree fallbacks carry the same names instead.

use eo9_store::{Name, Store};

use crate::cli::{Config, vlog};

// `EMBEDDED_COMPONENTS: &[(&str, &[u8])]`, generated by build.rs.
include!(concat!(env!("OUT_DIR"), "/embedded_components.rs"));

/// The bytes of an embedded component by file stem (e.g. `eosh`), if the binary carries
/// it.
pub fn embedded(stem: &str) -> Option<&'static [u8]> {
    EMBEDDED_COMPONENTS
        .iter()
        .find(|(name, _)| *name == stem)
        .map(|(_, bytes)| *bytes)
}

/// The shell name a built component file answers to: `eo9-example-hello` → `hello`,
/// `eo9-stub-time-frozen` → `time.frozen`, anything else (`eosh`) verbatim. `None` when
/// the result would not be a valid dotted name.
pub fn shell_name_for(stem: &str) -> Option<String> {
    let name = if let Some(example) = stem.strip_prefix("eo9-example-") {
        example.to_string()
    } else if let Some(stub) = stem.strip_prefix("eo9-stub-") {
        match stub.split_once('-') {
            Some((api, flavor)) => format!("{api}.{flavor}"),
            None => stub.to_string(),
        }
    } else {
        stem.to_string()
    };
    Name::parse(&name).ok().map(|_| name)
}

/// Seed an empty store from the embedded components: add each object and bind it under
/// its shell name. A store that already has any binding is left exactly as it is (user
/// bindings are never clobbered; running twice changes nothing). Returns how many names
/// were bound.
pub fn seed_store_if_empty(cfg: &Config, store: &Store) -> Result<usize, String> {
    let existing = store.names().map_err(|err| err.to_string())?;
    if !existing.is_empty() {
        vlog!(
            cfg,
            "store already has {} binding(s); not seeding",
            existing.len()
        );
        return Ok(0);
    }
    if EMBEDDED_COMPONENTS.is_empty() {
        vlog!(cfg, "no components are embedded in this build; not seeding");
        return Ok(0);
    }

    let mut bound = 0usize;
    for (stem, bytes) in EMBEDDED_COMPONENTS {
        let Some(shell_name) = shell_name_for(stem) else {
            continue;
        };
        let name = Name::parse(&shell_name).map_err(|err| err.to_string())?;
        let hash = store.add(bytes).map_err(|err| err.to_string())?;
        store.bind(&name, hash).map_err(|err| err.to_string())?;
        bound += 1;
    }
    if bound > 0 {
        eprintln!(
            "eo9: first run: seeded {bound} bundled programs into the module store at {}",
            store.root().display()
        );
    }
    Ok(bound)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn built_components_answer_to_their_shell_names() {
        assert_eq!(
            shell_name_for("eo9-example-hello").as_deref(),
            Some("hello")
        );
        assert_eq!(
            shell_name_for("eo9-example-readwrite").as_deref(),
            Some("readwrite")
        );
        assert_eq!(
            shell_name_for("eo9-stub-entropy-seeded").as_deref(),
            Some("entropy.seeded")
        );
        assert_eq!(
            shell_name_for("eo9-stub-time-monotonic-stub").as_deref(),
            Some("time.monotonic-stub")
        );
        assert_eq!(shell_name_for("eosh").as_deref(), Some("eosh"));
        // Something that cannot be a dotted name is skipped rather than mis-bound.
        assert_eq!(shell_name_for("Not A Name"), None);
    }

    #[test]
    fn every_embedded_component_has_a_shell_name() {
        for (stem, bytes) in EMBEDDED_COMPONENTS {
            assert!(
                shell_name_for(stem).is_some(),
                "embedded component {stem:?} has no shell name"
            );
            assert!(!bytes.is_empty(), "embedded component {stem:?} is empty");
        }
    }
}
