//! The embedded component set, first-run store seeding, and the upgrade refresh.
//!
//! The binary carries the components `cargo xtask build-guest` had produced when it was
//! built (eosh, the examples, the standard stubs — see `build.rs`). On the first start
//! against an **empty** store (no name bindings at all) they are added to the object
//! store and bound under their shell names, so a freshly installed `eo9` drops straight
//! into a working shell with programs to run.
//!
//! Seeding also leaves a small **seed record** at the store root (`<root>/seed`): the
//! fingerprint of the embedded set plus the hash each bundled name was bound to. That is
//! what makes upgrades safe: when a newer `eo9` opens a store seeded by an older one, the
//! fingerprints differ and [`ensure_seeded`] re-binds exactly the names that are still
//! the seeder's — a name the user re-bound (or added) is never touched, and no object is
//! ever deleted (`store gc` reclaims space). A store that predates the record is only
//! refreshed when it was itself seeded (the `eosh` binding is the tell); a store the user
//! assembled by hand stays exactly as it is. `eo9 store reseed` forces the same refresh
//! explicitly.
//!
//! In a checkout built before `build-guest` the embedded set is empty, nothing is seeded
//! or refreshed, and the dev-tree fallbacks carry the same names instead.

use std::collections::BTreeMap;
use std::fs;
use std::path::PathBuf;

use eo9_store::{Name, ObjectHash, Store};

use crate::cli::{Config, vlog};

// `EMBEDDED_COMPONENTS: &[(&str, &[u8])]`, generated by build.rs.
include!(concat!(env!("OUT_DIR"), "/embedded_components.rs"));

/// First line of the seed record at `<store-root>/seed`.
const SEED_RECORD_HEADER: &str = "eo9-seed 1";

/// The bytes of an embedded component by file stem (e.g. `eosh`), if the binary carries
/// it.
pub fn embedded(stem: &str) -> Option<&'static [u8]> {
    EMBEDDED_COMPONENTS
        .iter()
        .find(|(name, _)| *name == stem)
        .map(|(_, bytes)| *bytes)
}

/// The shell name a built component file answers to: `eo9-example-hello` → `hello`,
/// `eo9-coreutil-cat` → `cat`, `eo9-stub-time-frozen` → `time.frozen`, anything else
/// (`eosh`) verbatim. `None` when the result would not be a valid dotted name.
pub fn shell_name_for(stem: &str) -> Option<String> {
    let name = if let Some(example) = stem.strip_prefix("eo9-example-") {
        example.to_string()
    } else if let Some(coreutil) = stem.strip_prefix("eo9-coreutil-") {
        coreutil.to_string()
    } else if let Some(stub) = stem.strip_prefix("eo9-stub-") {
        match stub.split_once('-') {
            Some((api, flavor)) => format!("{api}.{flavor}"),
            None => stub.to_string(),
        }
    } else {
        stem.to_string()
    };
    Name::parse(&name).ok().map(|_| name)
}

/// Make sure the store's bundled programs match this binary.
///
/// * empty store → first-run seed (and write the seed record);
/// * seed record present and its fingerprint matches → nothing to do;
/// * fingerprint differs (the binary was upgraded) → refresh the names seeding still
///   owns;
/// * no record but the store was clearly seeded (an `eosh` binding exists) → refresh the
///   bundled names once and write the record;
/// * no record and no `eosh` binding (a store the user assembled by hand) → leave it
///   exactly as it is.
///
/// Returns how many names were bound or re-bound. Failures here should never block a
/// run: callers warn and continue (resolution then fails with its own message if the
/// store really is unusable).
pub fn ensure_seeded(cfg: &Config, store: &Store) -> Result<usize, String> {
    let set = embedded_set();
    if set.is_empty() {
        vlog!(cfg, "no components are embedded in this build; not seeding");
        return Ok(0);
    }
    let existing = store.names().map_err(|err| err.to_string())?;
    let fingerprint = embedded_fingerprint(&set);

    if existing.is_empty() {
        return first_seed(cfg, store, &set, &fingerprint);
    }

    match read_record(store) {
        Some(record) if record.fingerprint == fingerprint.to_string() => {
            vlog!(
                cfg,
                "bundled programs are current ({} seed-managed name(s))",
                record.entries.len()
            );
            Ok(0)
        }
        Some(record) => refresh(
            cfg,
            store,
            &set,
            &fingerprint,
            &existing,
            Managed::Recorded(&record.entries),
            true,
        ),
        None => {
            // A store from before the seed record existed. Only a store that was itself
            // seeded is refreshed implicitly — the `eosh` binding is the tell — so a
            // store the user assembled by hand is never touched behind their back.
            let eosh = Name::parse("eosh").expect("`eosh` is a valid store name");
            if existing.contains_key(&eosh) {
                vlog!(
                    cfg,
                    "store has bundled-program bindings but no seed record (seeded by an \
                     older eo9); refreshing them"
                );
                refresh(
                    cfg,
                    store,
                    &set,
                    &fingerprint,
                    &existing,
                    Managed::AllBundled,
                    true,
                )
            } else {
                vlog!(
                    cfg,
                    "store has {} binding(s), no seed record, and no `eosh` binding; \
                     leaving it alone",
                    existing.len()
                );
                Ok(0)
            }
        }
    }
}

/// `eo9 store reseed`: force the bundled-program refresh.
///
/// Same rules as [`ensure_seeded`]'s refresh — with a seed record, names the user
/// re-bound stay theirs; without one, every bundled name is refreshed — but it runs even
/// when the fingerprint already matches (recovery for an unbound or hand-edited name).
/// Returns how many names were bound or re-bound.
pub fn reseed(cfg: &Config, store: &Store) -> Result<usize, String> {
    let set = embedded_set();
    if set.is_empty() {
        return Err(
            "this eo9 binary has no bundled components to reseed from: build them first \
             (`cargo xtask build-guest`) and rebuild eo9, or use `eo9 store add`"
                .to_string(),
        );
    }
    let existing = store.names().map_err(|err| err.to_string())?;
    let fingerprint = embedded_fingerprint(&set);
    if existing.is_empty() {
        return first_seed(cfg, store, &set, &fingerprint);
    }
    let managed = read_record(store);
    refresh(
        cfg,
        store,
        &set,
        &fingerprint,
        &existing,
        match &managed {
            Some(record) => Managed::Recorded(&record.entries),
            None => Managed::AllBundled,
        },
        false,
    )
}

/// The embedded set as `(shell name, bytes)` pairs (components without a valid shell
/// name are skipped, exactly as seeding always has).
fn embedded_set() -> Vec<(String, &'static [u8])> {
    EMBEDDED_COMPONENTS
        .iter()
        .filter_map(|(stem, bytes)| shell_name_for(stem).map(|name| (name, *bytes)))
        .collect()
}

/// Fingerprint of the embedded component set: the blake3 hash of the sorted
/// `<name> <content-hash>` lines, so two binaries embedding identical components agree
/// regardless of where or when they were built.
fn embedded_fingerprint(set: &[(String, &'static [u8])]) -> ObjectHash {
    let mut lines: Vec<String> = set
        .iter()
        .map(|(name, bytes)| format!("{name} {}", ObjectHash::of(bytes)))
        .collect();
    lines.sort();
    ObjectHash::of(lines.join("\n").as_bytes())
}

/// Which bindings a refresh may touch.
enum Managed<'a> {
    /// A seed record exists: a name is still the seeder's iff its current binding is
    /// exactly what seeding bound it to. Anything else is the user's.
    Recorded(&'a BTreeMap<String, ObjectHash>),
    /// No record (a store seeded before records existed, or an explicit
    /// `store reseed` on one): every bundled name is treated as the seeder's.
    AllBundled,
}

/// First run against an empty store: add and bind every bundled component, write the
/// seed record.
fn first_seed(
    cfg: &Config,
    store: &Store,
    set: &[(String, &'static [u8])],
    fingerprint: &ObjectHash,
) -> Result<usize, String> {
    let mut entries = BTreeMap::new();
    let mut bound = 0usize;
    for (shell_name, bytes) in set {
        let name = Name::parse(shell_name).map_err(|err| err.to_string())?;
        let hash = store.add(bytes).map_err(|err| err.to_string())?;
        store.bind(&name, hash).map_err(|err| err.to_string())?;
        entries.insert(shell_name.clone(), hash);
        bound += 1;
    }
    write_record(cfg, store, fingerprint, &entries);
    if bound > 0 {
        eprintln!(
            "eo9: first run: seeded {bound} bundled programs into the module store at {}",
            store.root().display()
        );
    }
    Ok(bound)
}

/// Re-bind the bundled names this refresh owns to the components in this binary, leave
/// everything else alone, and write the new seed record. Objects are only ever added,
/// never removed.
fn refresh(
    cfg: &Config,
    store: &Store,
    set: &[(String, &'static [u8])],
    fingerprint: &ObjectHash,
    existing: &BTreeMap<Name, ObjectHash>,
    managed: Managed<'_>,
    announce: bool,
) -> Result<usize, String> {
    let mut entries = BTreeMap::new();
    let mut refreshed = 0usize;
    let mut left: Vec<String> = Vec::new();

    for (shell_name, bytes) in set {
        let name = Name::parse(shell_name).map_err(|err| err.to_string())?;
        let new_hash = ObjectHash::of(bytes);
        let current = existing.get(&name).copied();
        let still_the_seeders = match (current, &managed) {
            // Not bound at all: bind the bundled program (a tool added in this version,
            // or a binding the user removed and wants back via `reseed`).
            (None, _) => true,
            // The binding is exactly what seeding put there — refresh it.
            (Some(current), Managed::Recorded(record)) => record.get(shell_name) == Some(&current),
            // No provenance to consult: bundled names are the seeder's.
            (Some(_), Managed::AllBundled) => true,
        };
        if !still_the_seeders {
            left.push(shell_name.clone());
            continue;
        }
        if current != Some(new_hash) {
            let added = store.add(bytes).map_err(|err| err.to_string())?;
            store.bind(&name, added).map_err(|err| err.to_string())?;
            refreshed += 1;
        }
        entries.insert(shell_name.clone(), new_hash);
    }

    // Names seeding used to manage but this binary no longer bundles: keep their binding
    // (never delete), and keep them in the record while the binding still matches what
    // seeding put there, so a later binary that bundles them again may refresh them.
    if let Managed::Recorded(record) = managed {
        for (shell_name, hash) in record {
            if entries.contains_key(shell_name) {
                continue;
            }
            let still_bound_as_seeded = Name::parse(shell_name)
                .ok()
                .and_then(|name| existing.get(&name))
                .copied()
                == Some(*hash);
            if still_bound_as_seeded {
                entries.insert(shell_name.clone(), *hash);
            }
        }
    }

    write_record(cfg, store, fingerprint, &entries);
    if announce && refreshed > 0 {
        eprintln!("eo9: store: refreshed {refreshed} bundled program(s) for this version of eo9");
    }
    if !left.is_empty() {
        vlog!(
            cfg,
            "left {} user-bound name(s) untouched: {}",
            left.len(),
            left.join(", ")
        );
    }
    Ok(refreshed)
}

/// What seeding last did to this store: the embedded-set fingerprint of the binary that
/// seeded it and the hash each seed-managed name was bound to.
struct SeedRecord {
    fingerprint: String,
    entries: BTreeMap<String, ObjectHash>,
}

fn record_path(store: &Store) -> PathBuf {
    store.root().join("seed")
}

/// Read the seed record. Anything unreadable or malformed reads as "no record" — the
/// record is an upgrade marker, not user data, and the conservative legacy path handles
/// its absence.
fn read_record(store: &Store) -> Option<SeedRecord> {
    let text = fs::read_to_string(record_path(store)).ok()?;
    let mut lines = text
        .lines()
        .map(str::trim)
        .filter(|line| !line.is_empty() && !line.starts_with('#'));
    if lines.next() != Some(SEED_RECORD_HEADER) {
        return None;
    }
    let mut fingerprint = None;
    let mut entries = BTreeMap::new();
    for line in lines {
        let mut fields = line.split_whitespace();
        match (fields.next(), fields.next(), fields.next()) {
            (Some("fingerprint"), Some(value), None) => fingerprint = Some(value.to_string()),
            (Some(name), Some(hash), None) => {
                let valid_name = Name::parse(name).is_ok();
                let Ok(hash) = ObjectHash::from_hex(hash) else {
                    return None;
                };
                if !valid_name {
                    return None;
                }
                entries.insert(name.to_string(), hash);
            }
            _ => return None,
        }
    }
    Some(SeedRecord {
        fingerprint: fingerprint?,
        entries,
    })
}

/// Write the seed record. Failing to write it never blocks anything — the next start
/// simply re-checks (and the legacy path keeps working).
fn write_record(
    cfg: &Config,
    store: &Store,
    fingerprint: &ObjectHash,
    entries: &BTreeMap<String, ObjectHash>,
) {
    let mut text = format!("{SEED_RECORD_HEADER}\nfingerprint {fingerprint}\n");
    for (name, hash) in entries {
        text.push_str(&format!("{name} {hash}\n"));
    }
    if let Err(err) = fs::write(record_path(store), text) {
        vlog!(
            cfg,
            "cannot write the seed record {} (the next start will re-check): {err}",
            record_path(store).display()
        );
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn built_components_answer_to_their_shell_names() {
        assert_eq!(
            shell_name_for("eo9-example-hello").as_deref(),
            Some("hello")
        );
        assert_eq!(
            shell_name_for("eo9-example-readwrite").as_deref(),
            Some("readwrite")
        );
        assert_eq!(shell_name_for("eo9-coreutil-cat").as_deref(), Some("cat"));
        assert_eq!(shell_name_for("eo9-coreutil-rng").as_deref(), Some("rng"));
        assert_eq!(
            shell_name_for("eo9-stub-entropy-seeded").as_deref(),
            Some("entropy.seeded")
        );
        assert_eq!(
            shell_name_for("eo9-stub-time-monotonic-stub").as_deref(),
            Some("time.monotonic-stub")
        );
        assert_eq!(shell_name_for("eosh").as_deref(), Some("eosh"));
        // Something that cannot be a dotted name is skipped rather than mis-bound.
        assert_eq!(shell_name_for("Not A Name"), None);
    }

    #[test]
    fn every_embedded_component_has_a_shell_name() {
        for (stem, bytes) in EMBEDDED_COMPONENTS {
            assert!(
                shell_name_for(stem).is_some(),
                "embedded component {stem:?} has no shell name"
            );
            assert!(!bytes.is_empty(), "embedded component {stem:?} is empty");
        }
    }

    #[test]
    fn the_fingerprint_is_order_independent_and_content_sensitive() {
        let a: &[u8] = b"component a";
        let b: &[u8] = b"component b";
        let one = embedded_fingerprint(&[("x".to_string(), a), ("y".to_string(), b)]);
        let two = embedded_fingerprint(&[("y".to_string(), b), ("x".to_string(), a)]);
        assert_eq!(one, two, "ordering must not change the fingerprint");
        let three = embedded_fingerprint(&[("x".to_string(), b), ("y".to_string(), b)]);
        assert_ne!(one, three, "different contents must change the fingerprint");
    }

    #[test]
    fn the_seed_record_round_trips_and_tolerates_garbage() {
        let dir = std::env::temp_dir().join(format!(
            "eo9-seed-record-test-{}-{:?}",
            std::process::id(),
            std::thread::current().id()
        ));
        let _ = fs::remove_dir_all(&dir);
        let store = Store::open(&dir).expect("open a scratch store");
        let cfg = Config::default();

        assert!(read_record(&store).is_none(), "a fresh store has no record");

        let fingerprint = ObjectHash::of(b"set");
        let mut entries = BTreeMap::new();
        entries.insert("hello".to_string(), ObjectHash::of(b"hello"));
        entries.insert("entropy.seeded".to_string(), ObjectHash::of(b"seeded"));
        write_record(&cfg, &store, &fingerprint, &entries);

        let read = read_record(&store).expect("the record reads back");
        assert_eq!(read.fingerprint, fingerprint.to_string());
        assert_eq!(read.entries, entries);

        // A corrupt record reads as "no record" rather than failing the run.
        fs::write(record_path(&store), "not a seed record\n").unwrap();
        assert!(read_record(&store).is_none());

        let _ = fs::remove_dir_all(&dir);
    }
}
