//! Build-time extraction of the OS API describe cards from `wit/` doc comments.
//!
//! `describe eo9:pci` and `describe eo9:pci/pci` render cards (see `src/apidocs.rs`)
//! whose content comes from the WIT doc comments — the single authoritative place the
//! APIs are documented. Hand-maintained duplicates would rot, so this script parses the
//! repository's `wit/` tree at build time and bakes the extracted docs into a generated
//! table (`$OUT_DIR/api_docs.rs`). The `every_wit_package_and_interface_has_a_card` test
//! in `apidocs.rs` independently re-scans `wit/` and pins coverage, so a parser gap or a
//! new package without docs fails the build's test gate rather than shipping silent.
//!
//! The parser is deliberately line-oriented: our WIT style (one declaration per line,
//! `///` docs immediately above) is enforced by convention and `wit/check.sh`; this
//! script does not aspire to parse arbitrary WIT.

use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

/// The page terminal's column budget (mirrors `builtins.rs`); summaries are wrapped and
/// function lines truncated so every rendered card line fits.
const COLUMN_BUDGET: usize = 109;
/// Wrap width for summary paragraphs (leaves room for render-side prefixes).
const WRAP_WIDTH: usize = 105;

struct PackageDoc {
    name: String,
    version: String,
    summary: Vec<String>,
    interfaces: Vec<(String, String)>,
    worlds: Vec<String>,
}

struct InterfaceDoc {
    package: String,
    name: String,
    version: String,
    summary: Vec<String>,
    functions: Vec<(String, String)>,
}

fn main() {
    let manifest = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let wit_root = manifest
        .join("../../../wit")
        .canonicalize()
        .expect("the wit/ tree exists three levels up from eosh-core");
    println!("cargo:rerun-if-changed={}", wit_root.display());

    let mut packages: Vec<PackageDoc> = Vec::new();
    let mut interfaces: Vec<InterfaceDoc> = Vec::new();

    let mut dirs: Vec<PathBuf> = fs::read_dir(&wit_root)
        .expect("read wit/")
        .filter_map(|e| e.ok())
        .map(|e| e.path())
        .filter(|p| p.is_dir())
        .collect();
    dirs.sort();

    for dir in dirs {
        let mut files: Vec<PathBuf> = fs::read_dir(&dir)
            .expect("read wit package dir")
            .filter_map(|e| e.ok())
            .map(|e| e.path())
            .filter(|p| p.extension().is_some_and(|x| x == "wit"))
            .collect();
        files.sort();
        for file in files {
            parse_wit_file(&file, &mut packages, &mut interfaces);
        }
    }

    packages.sort_by(|a, b| a.name.cmp(&b.name));
    interfaces.sort_by(|a, b| (&a.package, &a.name).cmp(&(&b.package, &b.name)));

    let mut out = String::new();
    out.push_str(
        "// Generated by eosh-core/build.rs from the repository's wit/ tree. Do not edit.\n",
    );
    out.push_str("pub static API_PACKAGES: &[ApiPackageDoc] = &[\n");
    for p in &packages {
        let _ = writeln!(
            out,
            "    ApiPackageDoc {{ name: {:?}, version: {:?}, summary: &{:?}, interfaces: &{:?}, worlds: &{:?} }},",
            p.name, p.version, p.summary, p.interfaces, p.worlds
        );
    }
    out.push_str("];\n");
    out.push_str("pub static API_INTERFACES: &[ApiInterfaceDoc] = &[\n");
    for i in &interfaces {
        let _ = writeln!(
            out,
            "    ApiInterfaceDoc {{ package: {:?}, name: {:?}, version: {:?}, summary: &{:?}, functions: &{:?} }},",
            i.package, i.name, i.version, i.summary, i.functions
        );
    }
    out.push_str("];\n");

    let out_path = Path::new(&env::var("OUT_DIR").expect("OUT_DIR")).join("api_docs.rs");
    fs::write(&out_path, out).expect("write api_docs.rs");
}

/// Parse one `.wit` file, appending its package and interfaces.
fn parse_wit_file(path: &Path, packages: &mut Vec<PackageDoc>, interfaces: &mut Vec<InterfaceDoc>) {
    let text = fs::read_to_string(path).expect("read wit file");

    let mut docbuf: Vec<String> = Vec::new();
    let mut package_name = String::new();
    let mut package_version = String::new();
    let mut depth: i32 = 0;
    // (name, version-suffix-stripped docs, functions) for the interface being walked.
    let mut current: Option<InterfaceDoc> = None;

    for raw in text.lines() {
        let line = raw.trim_end();
        let trimmed = line.trim_start();

        if let Some(doc) = trimmed.strip_prefix("///") {
            docbuf.push(doc.strip_prefix(' ').unwrap_or(doc).to_string());
            continue;
        }

        if depth == 0 {
            if let Some(rest) = trimmed.strip_prefix("package ") {
                let decl = rest.trim_end_matches(';');
                let (name, version) = decl.split_once('@').unwrap_or((decl, ""));
                package_name = name.trim().to_string();
                package_version = version.trim().to_string();
                packages.push(PackageDoc {
                    name: package_name.clone(),
                    version: package_version.clone(),
                    summary: wrap(&first_paragraph(&docbuf)),
                    interfaces: Vec::new(),
                    worlds: Vec::new(),
                });
                docbuf.clear();
                continue;
            }
            if let Some(rest) = trimmed.strip_prefix("interface ") {
                let name = rest.split_whitespace().next().unwrap_or("").to_string();
                let summary = first_paragraph(&docbuf);
                let full = format!("{package_name}/{name}");
                // Truncate so the package card's `  full — one-liner` line fits.
                let budget = COLUMN_BUDGET.saturating_sub(2 + full.chars().count() + 3);
                let one_liner = truncate(&first_sentence(&summary), budget);
                if let Some(p) = packages.iter_mut().find(|p| p.name == package_name) {
                    p.interfaces.push((full, one_liner));
                }
                current = Some(InterfaceDoc {
                    package: package_name.clone(),
                    name,
                    version: package_version.clone(),
                    summary: wrap(&summary),
                    functions: Vec::new(),
                });
            } else if let Some(rest) = trimmed.strip_prefix("world ") {
                let name = rest.split_whitespace().next().unwrap_or("").to_string();
                if let Some(p) = packages.iter_mut().find(|p| p.name == package_name) {
                    p.worlds.push(name);
                }
            }
        } else if depth == 1
            && current.is_some()
            && let Some((name, rest)) = trimmed.split_once(':')
            && is_wit_ident(name)
            && (rest.trim_start().starts_with("func")
                || rest.trim_start().starts_with("async func"))
        {
            let summary = first_sentence(&first_paragraph(&docbuf));
            let iface = current.as_mut().expect("checked above");
            // Truncate so the rendered `  name — summary` line fits the budget.
            let prefix_len = 2 + name.chars().count() + 3;
            let budget = COLUMN_BUDGET.saturating_sub(prefix_len);
            iface
                .functions
                .push((name.to_string(), truncate(&summary, budget)));
        }

        // Doc comments attach only to the immediately following declaration.
        docbuf.clear();

        // Track brace depth from code lines (strings in our WIT carry no braces).
        for c in line.chars() {
            match c {
                '{' => depth += 1,
                '}' => {
                    depth -= 1;
                    if depth == 0
                        && let Some(done) = current.take()
                    {
                        interfaces.push(done);
                    }
                }
                _ => {}
            }
        }
    }
}

/// A WIT identifier: lowercase words, digits, hyphens (also `%`-prefixed escapes).
fn is_wit_ident(s: &str) -> bool {
    !s.is_empty()
        && s.chars()
            .all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || c == '-' || c == '%')
}

/// The first doc paragraph (up to the first blank line), joined into flowing text.
fn first_paragraph(docs: &[String]) -> String {
    docs.iter()
        .take_while(|l| !l.trim().is_empty())
        .map(|l| l.trim())
        .collect::<Vec<_>>()
        .join(" ")
}

/// The first sentence of flowing text (for one-line listings).
fn first_sentence(text: &str) -> String {
    match text.find(". ") {
        Some(i) => text[..i + 1].to_string(),
        None => text.to_string(),
    }
}

/// Greedy word wrap to `WRAP_WIDTH`.
fn wrap(text: &str) -> Vec<String> {
    let mut lines = Vec::new();
    let mut line = String::new();
    for word in text.split_whitespace() {
        if !line.is_empty() && line.chars().count() + 1 + word.chars().count() > WRAP_WIDTH {
            lines.push(core::mem::take(&mut line));
        }
        if !line.is_empty() {
            line.push(' ');
        }
        line.push_str(word);
    }
    if !line.is_empty() {
        lines.push(line);
    }
    lines
}

/// Truncate to `budget` characters, with an ellipsis when cut.
fn truncate(text: &str, budget: usize) -> String {
    if text.chars().count() <= budget {
        return text.to_string();
    }
    let cut: String = text.chars().take(budget.saturating_sub(1)).collect();
    format!("{}…", cut.trim_end())
}
