//! End-to-end tests of the `eo9` binary against the merged example components
//! (plan/11-usermode.md): `run` of hello / outcomes / cruncher with the three-way
//! outcome and exit codes, compile-cache behaviour on a second run, the memory-limit
//! flag, store-resolved names, `describe`, `compile`, `store` subcommands, and the
//! readwrite end to end through the unix fs provider, and `shell` transcripts (one-shot
//! `-c` commands and a piped interactive session) running eosh against the session view.
//!
//! The tests drive the real binary (`CARGO_BIN_EXE_eo9`) as a subprocess, with the
//! module store pointed at a per-test directory under `CARGO_TARGET_TMPDIR`. Example
//! components are built on demand with `cargo xtask build-guest` if they are missing.

use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;
use std::sync::Once;

const EXAMPLES: &[&str] = &["hello", "outcomes", "cruncher", "readwrite"];

fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../..")
        .canonicalize()
        .expect("repository root must exist")
}

fn component_path(name: &str) -> PathBuf {
    repo_root()
        .join("guest/target/components")
        .join(format!("eo9-example-{name}.wasm"))
}

/// Build the example components (once per test process) if any are missing. When they
/// had to be built, the eo9 binary under test is rebuilt too, so its embedded component
/// set (generated by build.rs from the same directory) is no longer empty.
fn ensure_components() {
    static BUILD: Once = Once::new();
    BUILD.call_once(|| {
        if EXAMPLES.iter().all(|name| component_path(name).exists()) {
            return;
        }
        let status = Command::new("cargo")
            .args(["run", "-p", "xtask", "--", "build-guest"])
            .current_dir(repo_root())
            .status()
            .expect("failed to invoke `cargo run -p xtask -- build-guest`");
        assert!(status.success(), "xtask build-guest failed");

        let status = Command::new("cargo")
            .args(["build", "-p", "eo9"])
            .current_dir(repo_root())
            .status()
            .expect("failed to rebuild the eo9 binary after build-guest");
        assert!(status.success(), "rebuilding eo9 after build-guest failed");
    });
    for name in EXAMPLES {
        assert!(
            component_path(name).exists(),
            "missing example component {}",
            component_path(name).display()
        );
    }
}

/// A fresh store root for one test.
fn temp_store(test: &str) -> PathBuf {
    let dir = Path::new(env!("CARGO_TARGET_TMPDIR")).join(format!("eo9-cli-{test}"));
    if dir.exists() {
        fs::remove_dir_all(&dir).expect("failed to clear the test store");
    }
    fs::create_dir_all(&dir).expect("failed to create the test store");
    dir
}

struct Run {
    code: i32,
    stdout: String,
    stderr: String,
}

/// Run the eo9 binary with `args`, using `store` as the module store root.
fn eo9(store: &Path, args: &[&str]) -> Run {
    eo9_with_stdin(store, args, None)
}

/// Run the eo9 binary, optionally feeding `stdin` (used for interactive-shell
/// transcripts; the text provider reads the piped stream like any stdin).
fn eo9_with_stdin(store: &Path, args: &[&str], stdin: Option<&str>) -> Run {
    use std::io::Write as _;
    use std::process::Stdio;

    ensure_components();
    let mut command = Command::new(env!("CARGO_BIN_EXE_eo9"));
    command
        .args(args)
        .env("EO9_STORE", store)
        .current_dir(repo_root())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .stdin(if stdin.is_some() {
            Stdio::piped()
        } else {
            Stdio::null()
        });
    let mut child = command.spawn().expect("failed to start the eo9 binary");
    if let Some(script) = stdin {
        child
            .stdin
            .take()
            .expect("stdin was piped")
            .write_all(script.as_bytes())
            .expect("failed to write the shell transcript");
    }
    let output = child
        .wait_with_output()
        .expect("failed to run the eo9 binary");
    Run {
        code: output.status.code().expect("eo9 exited without a code"),
        stdout: String::from_utf8_lossy(&output.stdout).into_owned(),
        stderr: String::from_utf8_lossy(&output.stderr).into_owned(),
    }
}

fn component_arg(name: &str) -> String {
    component_path(name)
        .to_str()
        .expect("utf-8 path")
        .to_owned()
}

// -----------------------------------------------------------------------------------
// run: the example binaries end to end
// -----------------------------------------------------------------------------------

#[test]
fn run_hello_by_path_end_to_end() {
    let store = temp_store("run-hello");
    let hello = component_arg("hello");
    let run = eo9(
        &store,
        &["run", &hello, "--name", "eo9", "--excited", "true"],
    );
    assert_eq!(run.code, 0, "stderr: {}", run.stderr);
    assert!(
        run.stdout.contains("Hello, eo9!"),
        "program output missing from stdout: {}",
        run.stdout
    );
    assert_eq!(
        run.stdout.lines().last(),
        Some("success(greeted)"),
        "outcome line missing from stdout: {}",
        run.stdout
    );
}

#[test]
fn run_outcomes_covers_success_failure_and_abnormal() {
    let store = temp_store("run-outcomes");
    let outcomes = component_arg("outcomes");
    let run_mode = |mode: &str, detail: &str| {
        eo9(
            &store,
            &["run", &outcomes, "--mode", mode, "--detail", detail],
        )
    };

    let ok = run_mode("ok", "all good");
    assert_eq!(ok.code, 0, "stderr: {}", ok.stderr);
    assert_eq!(
        ok.stdout.lines().last(),
        Some("success(completed(\"all good\"))")
    );

    let quiet = run_mode("quiet", "");
    assert_eq!(quiet.code, 0, "stderr: {}", quiet.stderr);
    assert_eq!(quiet.stdout.trim(), "success(quiet)");

    let fail = run_mode("fail", "went wrong");
    assert_eq!(fail.code, 1, "stderr: {}", fail.stderr);
    assert_eq!(
        fail.stdout.lines().last(),
        Some("failure(requested-failure(\"went wrong\"))")
    );

    let rejected = run_mode("nonsense", "");
    assert_eq!(rejected.code, 1, "stderr: {}", rejected.stderr);
    assert!(
        rejected.stdout.trim().starts_with("failure(bad-arguments("),
        "unexpected outcome: {}",
        rejected.stdout
    );

    // A guest panic lowers to a wasm trap: the executor's abnormal arm, exit code 2.
    let trapped = run_mode("trap", "");
    assert_eq!(trapped.code, 2, "stderr: {}", trapped.stderr);
    assert!(
        trapped.stdout.trim().starts_with("abnormal(trapped("),
        "unexpected outcome: {}",
        trapped.stdout
    );
    assert!(
        trapped.stdout.contains("unreachable"),
        "trap reason missing: {}",
        trapped.stdout
    );
}

#[test]
fn run_cruncher_is_deterministic_pure_compute() {
    let store = temp_store("run-cruncher");
    let cruncher = component_arg("cruncher");

    // The same splitmix64 mix as the example, so the digest can be checked exactly.
    fn mix(state: u64) -> u64 {
        let mut z = state.wrapping_add(0x9e37_79b9_7f4a_7c15);
        z = (z ^ (z >> 30)).wrapping_mul(0xbf58_476d_1ce4_e5b9);
        z = (z ^ (z >> 27)).wrapping_mul(0x94d0_49bb_1331_11eb);
        z ^ (z >> 31)
    }
    let expected = (0..1000).fold(9u64, |digest, _| mix(digest));

    let first = eo9(
        &store,
        &["run", &cruncher, "--seed", "9", "--rounds", "1000"],
    );
    assert_eq!(first.code, 0, "stderr: {}", first.stderr);
    assert_eq!(first.stdout.trim(), format!("success(digest({expected}))"));

    // Pure compute with fixed arguments is bit-deterministic run to run.
    let second = eo9(
        &store,
        &["run", &cruncher, "--seed", "9", "--rounds", "1000"],
    );
    assert_eq!(second.code, 0, "stderr: {}", second.stderr);
    assert_eq!(second.stdout, first.stdout);

    // Zero rounds is rejected in the program's own failure vocabulary.
    let rejected = eo9(&store, &["run", &cruncher, "--seed", "9", "--rounds", "0"]);
    assert_eq!(rejected.code, 1);
    assert!(rejected.stdout.trim().starts_with("failure(bad-arguments("));
}

// -----------------------------------------------------------------------------------
// Compile cache
// -----------------------------------------------------------------------------------

#[test]
fn second_run_launches_from_the_cached_image() {
    let store = temp_store("cache-hit");
    let cruncher = component_arg("cruncher");
    let args = ["-v", "run", &cruncher, "--seed", "1", "--rounds", "10"];

    let first = eo9(&store, &args);
    assert_eq!(first.code, 0, "stderr: {}", first.stderr);
    assert!(
        first.stderr.contains("compile cache miss"),
        "first run should miss: {}",
        first.stderr
    );
    assert!(
        first.stderr.contains("cached image"),
        "first run should cache the image it compiled: {}",
        first.stderr
    );

    // The second run takes the cached path: it deserializes the stored image and never
    // reaches codegen (no "compiling"/"compiled" diagnostics), yet the outcome is
    // identical.
    let second = eo9(&store, &args);
    assert_eq!(second.code, 0, "stderr: {}", second.stderr);
    assert!(
        second.stderr.contains("launched from cached image"),
        "second run should launch from the cache: {}",
        second.stderr
    );
    assert!(
        !second.stderr.contains("compiling") && !second.stderr.contains("compiled"),
        "second run must not pay codegen: {}",
        second.stderr
    );
    assert_eq!(second.stdout, first.stdout);

    // The store's cache entry records both uses (insert counts as the first).
    let cache_dir = store.join("cache");
    let mut use_counts = Vec::new();
    for entry in fs::read_dir(&cache_dir).expect("cache directory must exist") {
        let meta = entry.expect("readable cache entry").path().join("meta");
        let text = fs::read_to_string(meta).expect("readable cache metadata");
        let count = text
            .lines()
            .find_map(|line| line.strip_prefix("use-count "))
            .expect("metadata carries a use-count")
            .parse::<u64>()
            .expect("use-count is a number");
        use_counts.push(count);
    }
    assert_eq!(
        use_counts,
        vec![2],
        "unexpected cache usage: {use_counts:?}"
    );
}

#[test]
fn corrupted_cache_entries_are_ignored_not_trusted() {
    let store = temp_store("cache-corrupt");
    let cruncher = component_arg("cruncher");
    let args = ["-v", "run", &cruncher, "--seed", "3", "--rounds", "10"];

    let first = eo9(&store, &args);
    assert_eq!(first.code, 0, "stderr: {}", first.stderr);

    // Flip the last byte of the cached artifact: the envelope's recorded content hash no
    // longer matches, so the entry must be refused and the component recompiled.
    let cache_dir = store.join("cache");
    let entry = fs::read_dir(&cache_dir)
        .expect("cache directory must exist")
        .next()
        .expect("one cache entry")
        .expect("readable cache entry");
    let image_path = entry.path().join("image");
    let mut bytes = fs::read(&image_path).expect("readable cached image");
    let last = bytes.len() - 1;
    bytes[last] ^= 0x01;
    fs::write(&image_path, &bytes).expect("cached image is writable in the test store");

    let second = eo9(&store, &args);
    assert_eq!(second.code, 0, "stderr: {}", second.stderr);
    assert!(
        second.stderr.contains("ignoring compile-cache entry"),
        "the tampered entry should be refused: {}",
        second.stderr
    );
    assert!(
        !second.stderr.contains("launched from cached image"),
        "the tampered entry must not be launched: {}",
        second.stderr
    );
    assert_eq!(second.stdout, first.stdout);
}

#[test]
fn an_unwritable_cache_never_fails_a_run() {
    use std::os::unix::fs::PermissionsExt;

    fn set_mode(path: &Path, mode: u32) {
        fs::set_permissions(path, fs::Permissions::from_mode(mode))
            .unwrap_or_else(|err| panic!("cannot chmod {}: {err}", path.display()));
    }

    let store = temp_store("cache-readonly");
    let cruncher = component_arg("cruncher");
    let args = ["-v", "run", &cruncher, "--seed", "5", "--rounds", "10"];

    // Cold cache, read-only cache directory: the insert after compiling fails, the run
    // still succeeds with a warning.
    let cache_dir = store.join("cache");
    fs::create_dir_all(&cache_dir).expect("create the cache directory");
    set_mode(&cache_dir, 0o555);
    let cold = eo9(&store, &args);
    set_mode(&cache_dir, 0o755);
    assert_eq!(cold.code, 0, "stderr: {}", cold.stderr);
    assert!(
        cold.stderr.contains("could not be cached"),
        "expected an insert warning: {}",
        cold.stderr
    );
    assert!(cold.stdout.trim().starts_with("success(digest("));

    // Populate the cache normally, then make the entry read-only: the lookup's
    // use-count bump fails, which is treated as a miss (warn + recompile), not an error.
    let warm = eo9(&store, &args);
    assert_eq!(warm.code, 0, "stderr: {}", warm.stderr);
    let entry_dir = fs::read_dir(&cache_dir)
        .expect("cache directory must exist")
        .next()
        .expect("one cache entry")
        .expect("readable cache entry")
        .path();
    set_mode(&entry_dir, 0o555);
    let bumped = eo9(&store, &args);
    set_mode(&entry_dir, 0o755);
    assert_eq!(bumped.code, 0, "stderr: {}", bumped.stderr);
    assert!(
        bumped.stderr.contains("compile-cache lookup failed"),
        "expected a lookup warning: {}",
        bumped.stderr
    );
    assert_eq!(bumped.stdout, cold.stdout);
}

#[test]
fn compile_warms_the_cache_for_a_later_run() {
    let store = temp_store("compile-warm");
    let outcomes = component_arg("outcomes");

    let warm = eo9(&store, &["compile", &outcomes]);
    assert_eq!(warm.code, 0, "stderr: {}", warm.stderr);
    assert!(
        warm.stdout.starts_with("compiled and cached:"),
        "unexpected compile output: {}",
        warm.stdout
    );

    let run = eo9(
        &store,
        &["-v", "run", &outcomes, "--mode", "quiet", "--detail", ""],
    );
    assert_eq!(run.code, 0, "stderr: {}", run.stderr);
    assert!(
        run.stderr.contains("launched from cached image"),
        "run after warm should launch from the cache: {}",
        run.stderr
    );

    let rewarm = eo9(&store, &["compile", &outcomes]);
    assert_eq!(rewarm.code, 0);
    assert!(rewarm.stdout.starts_with("compile cache hit:"));
}

// -----------------------------------------------------------------------------------
// Limits and refusal paths
// -----------------------------------------------------------------------------------

#[test]
fn memory_limit_flag_is_enforced() {
    let store = temp_store("memory-limit");
    let cruncher = component_arg("cruncher");

    // Far below the component's initial linear memory: the limiter refuses the very
    // first allocation and the spawn fails before any guest code runs.
    let denied = eo9(
        &store,
        &[
            "--max-memory",
            "65536",
            "run",
            &cruncher,
            "--seed",
            "1",
            "--rounds",
            "10",
        ],
    );
    assert_eq!(denied.code, 3, "stdout: {}", denied.stdout);
    assert!(
        denied.stderr.contains("memory"),
        "expected a memory-limit spawn error: {}",
        denied.stderr
    );

    // A generous ceiling changes nothing about a well-behaved program.
    let allowed = eo9(
        &store,
        &[
            "--max-memory",
            "67108864",
            "run",
            &cruncher,
            "--seed",
            "1",
            "--rounds",
            "10",
        ],
    );
    assert_eq!(allowed.code, 0, "stderr: {}", allowed.stderr);
}

#[test]
fn readwrite_round_trips_through_the_unix_fs() {
    // The async fs example end to end from the CLI: the program's eo9:fs capability is
    // the unix fs provider rooted at --fs-root, the owned-buffer write/read round-trip
    // goes through real host files, and the outcome is the program's own success value.
    let store = temp_store("readwrite");
    let fs_root = temp_store("readwrite-fsroot");
    let readwrite = component_arg("readwrite");
    let run = eo9(
        &store,
        &[
            "--fs-root",
            fs_root.to_str().expect("utf-8 fs root"),
            "run",
            &readwrite,
            "--path",
            "note.txt",
            "--contents",
            "hello disk",
        ],
    );
    assert_eq!(run.code, 0, "stderr: {}", run.stderr);
    assert_eq!(run.stdout.trim(), "success(round-tripped(10))");

    // The write really landed on the host filesystem, under the fs root.
    assert_eq!(
        fs::read_to_string(fs_root.join("note.txt")).expect("note.txt exists under the fs root"),
        "hello disk"
    );
}

#[test]
fn readwrite_failures_stay_in_the_programs_vocabulary_and_inside_the_root() {
    let store = temp_store("readwrite-fail");
    let fs_root = temp_store("readwrite-fail-fsroot");
    let readwrite = component_arg("readwrite");
    let run_with_path = |path: &str| {
        eo9(
            &store,
            &[
                "--fs-root",
                fs_root.to_str().expect("utf-8 fs root"),
                "run",
                &readwrite,
                "--path",
                path,
                "--contents",
                "should not land",
            ],
        )
    };

    // A path that tries to climb out of the fs root is refused by the provider's
    // containment and surfaces as the program's own fs(...) failure case.
    let escape = run_with_path("../escaped.txt");
    assert_eq!(escape.code, 1, "stderr: {}", escape.stderr);
    assert!(
        escape.stdout.trim().starts_with("failure(fs("),
        "expected the program's fs failure: {}",
        escape.stdout
    );
    assert!(
        escape.stdout.contains("Denied"),
        "expected a denied error: {}",
        escape.stdout
    );
    assert!(
        !fs_root
            .parent()
            .expect("fs root has a parent")
            .join("escaped.txt")
            .exists(),
        "nothing may be created outside the fs root"
    );

    // Opening inside a directory that does not exist fails through the provider and is
    // reported the same way (not-found, in the program's vocabulary).
    let missing = run_with_path("no-such-dir/note.txt");
    assert_eq!(missing.code, 1, "stderr: {}", missing.stderr);
    assert!(
        missing.stdout.trim().starts_with("failure(fs("),
        "expected the program's fs failure: {}",
        missing.stdout
    );
}

#[test]
fn fs_is_not_granted_without_an_explicit_fs_root() {
    // No ambient filesystem authority: without --fs-root there is no fs provider at all,
    // and a program that requires eo9:fs is refused before it runs, with a hint that
    // names the flag.
    let store = temp_store("readwrite-no-grant");
    let readwrite = component_arg("readwrite");
    let run = eo9(
        &store,
        &[
            "run",
            &readwrite,
            "--path",
            "note.txt",
            "--contents",
            "should never land",
        ],
    );
    assert_eq!(run.code, 3, "stdout: {}", run.stdout);
    assert!(
        run.stderr.contains("--fs-root"),
        "the refusal should point at --fs-root: {}",
        run.stderr
    );
    assert!(
        run.stderr.contains("eo9:fs"),
        "the refusal should name the missing capability: {}",
        run.stderr
    );
    // And nothing was written anywhere (the repo root is eo9's cwd in these tests).
    assert!(!repo_root().join("note.txt").exists());
}

#[test]
fn missing_arguments_are_a_spawn_error() {
    let store = temp_store("missing-args");
    let hello = component_arg("hello");
    let run = eo9(&store, &["run", &hello, "--name", "eo9"]);
    assert_eq!(run.code, 3, "stdout: {}", run.stdout);
    assert!(
        run.stderr.contains("missing argument `excited`"),
        "unexpected error: {}",
        run.stderr
    );
}

// -----------------------------------------------------------------------------------
// The shell (eosh running under `eo9 shell`)
// -----------------------------------------------------------------------------------

#[test]
fn shell_runs_a_program_by_bare_name() {
    // One-shot mode: eosh resolves `hello` as /bin/hello.wasm on the session fs (seeded
    // from the dev-tree components here), composes nothing, compiles, spawns it as a
    // child with the session root providers, and renders the child's own outcome.
    let store = temp_store("shell-hello");
    let run = eo9(
        &store,
        &["shell", "-c", "hello --name shell --excited true"],
    );
    assert_eq!(run.code, 0, "stderr: {}", run.stderr);
    assert!(run.stdout.contains("Hello, shell!"), "{}", run.stdout);
    assert!(run.stdout.contains("ok: greeted"), "{}", run.stdout);
}

#[test]
fn shell_describe_builtin_inspects_without_running() {
    let store = temp_store("shell-describe");
    let run = eo9(&store, &["shell", "-c", "describe hello"]);
    assert_eq!(run.code, 0, "stderr: {}", run.stderr);
    assert!(run.stdout.contains("kind: binary"), "{}", run.stdout);
    assert!(run.stdout.contains("--name: string"), "{}", run.stdout);
    assert!(run.stdout.contains("eo9:text/text"), "{}", run.stdout);
    // Describing does not run the program.
    assert!(!run.stdout.contains("Hello"), "{}", run.stdout);
}

#[test]
fn shell_composes_with_the_algebra() {
    // An (unconfigured) provider composed onto a pure-compute binary: `$` goes through
    // eosh's algebra imports, the result compiles and runs, and the digest matches what
    // the same seed produces under `eo9 run` (composition with an unused provider is the
    // identity on behaviour).
    let store = temp_store("shell-compose");
    let run = eo9(
        &store,
        &[
            "shell",
            "-c",
            "entropy.seeded $ cruncher --seed 3 --rounds 100",
        ],
    );
    assert_eq!(run.code, 0, "stderr: {}", run.stderr);
    assert!(run.stdout.contains("ok: digest("), "{}", run.stdout);

    let direct = eo9(
        &store,
        &[
            "run",
            &component_arg("cruncher"),
            "--seed",
            "3",
            "--rounds",
            "100",
        ],
    );
    let digest = |text: &str| {
        text.lines()
            .find_map(|line| {
                let start = line.find("digest(")?;
                line[start..]
                    .strip_prefix("digest(")?
                    .split(')')
                    .next()
                    .map(str::to_owned)
            })
            .expect("a digest in the output")
    };
    assert_eq!(digest(&run.stdout), digest(&direct.stdout));
}

#[test]
fn shell_maps_child_failures_to_exit_code_1() {
    let store = temp_store("shell-fail");
    let failed = eo9(
        &store,
        &["shell", "-c", "outcomes --mode fail --detail boom"],
    );
    assert_eq!(failed.code, 1, "stdout: {}", failed.stdout);
    assert!(
        failed.stdout.contains("error: requested-failure(\"boom\")"),
        "{}",
        failed.stdout
    );
    assert!(
        failed.stdout.contains("failure(command-failed("),
        "the shell's own outcome should be a failure: {}",
        failed.stdout
    );

    let unknown = eo9(&store, &["shell", "-c", "nosuchprogram"]);
    assert_eq!(unknown.code, 1, "stdout: {}", unknown.stdout);
    assert!(
        unknown.stdout.contains("cannot resolve `nosuchprogram`"),
        "{}",
        unknown.stdout
    );
}

#[test]
fn shell_interactive_transcript_with_let_bindings() {
    // Interactive mode over a piped stdin (no TTY needed): a `let` binding, a use of it
    // with flags, and a clean exit.
    let store = temp_store("shell-interactive");
    let run = eo9_with_stdin(
        &store,
        &["shell"],
        Some("let h = hello\nh --name fromlet --excited true\nexit\n"),
    );
    assert_eq!(run.code, 0, "stderr: {}", run.stderr);
    assert!(run.stdout.contains("eosh>"), "{}", run.stdout);
    assert!(run.stdout.contains("Hello, fromlet!"), "{}", run.stdout);
    assert!(run.stdout.contains("ok: greeted"), "{}", run.stdout);
}

/// Regression test for the duplicated interactive prompt: pressing Enter on a line that
/// produces no stdout (an empty line, a parse error) must not make the next repaint show
/// `eosh> eosh> …`. The interactive path needs a real terminal, so the shell is run
/// inside a pseudo-terminal via script(1); the BSD invocation used here is macOS-only
/// (which is also the only place `cargo xtask ci` runs today).
#[test]
#[cfg(target_os = "macos")]
fn shell_interactive_pty_prompt_is_not_duplicated() {
    use std::io::Write as _;
    use std::process::Stdio;
    use std::time::Duration;

    ensure_components();
    let store = temp_store("shell-pty-prompt");

    // Warm the store seeding and the eosh compile cache first (no pty), so the pty
    // session below reaches its first interactive read quickly and the paced input
    // arrives after the editor owns the terminal.
    let warm = eo9(&store, &["shell", "-c", "help"]);
    assert_eq!(warm.code, 0, "stderr: {}", warm.stderr);

    let mut child = Command::new("/usr/bin/script")
        .args(["-q", "/dev/null", env!("CARGO_BIN_EXE_eo9"), "shell"])
        .env("EO9_STORE", &store)
        .current_dir(repo_root())
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .expect("failed to start script(1) with the eo9 shell");

    // Paced keystrokes: empty Enters, a command with output, a parse error (stderr
    // only), then exit. The pauses keep each line's processing apart; exact timing is
    // not load-bearing for the assertion (a duplicate would persist in the repaints).
    {
        let stdin = child.stdin.as_mut().expect("stdin was piped");
        let mut send = |bytes: &[u8], wait_ms: u64| {
            stdin.write_all(bytes).expect("write to the pty");
            stdin.flush().expect("flush the pty");
            std::thread::sleep(Duration::from_millis(wait_ms));
        };
        std::thread::sleep(Duration::from_millis(1500));
        send(b"\r", 400);
        send(b"\r", 400);
        send(b"hello --name pty --excited true\r", 1500);
        send(b"\r", 400);
        send(b"badsyntax )\r", 600);
        send(b"exit\r", 600);
    }
    drop(child.stdin.take());

    let output = child
        .wait_with_output()
        .expect("script(1) session did not finish");
    let stdout = String::from_utf8_lossy(&output.stdout).into_owned();

    // The interactive editor ran (prompt repaints use clear-line escapes)…
    assert!(stdout.contains("eosh>"), "no prompt seen: {stdout:?}");
    assert!(
        stdout.contains("\u{1b}[2K"),
        "the interactive editor did not run (no repaints): {stdout:?}"
    );
    // …and no repaint ever stacked one prompt onto another.
    assert!(
        !stdout.contains("eosh> eosh>"),
        "duplicated prompt in the interactive session: {stdout:?}"
    );
}

#[test]
fn shell_resolves_store_bound_names_and_eosh_from_the_store() {
    // Bind eosh and a program under a name that exists only in the store: the session
    // bin view must come from the store bindings (hardlinks to store objects), not from
    // the dev tree, and eosh itself must be found via its store binding.
    let store = temp_store("shell-store-names");
    let add_eosh = eo9(
        &store,
        &[
            "store",
            "add",
            &component_path("hello")
                .with_file_name("eosh.wasm")
                .display()
                .to_string(),
            "--name",
            "eosh",
        ],
    );
    assert_eq!(add_eosh.code, 0, "stderr: {}", add_eosh.stderr);
    let add_greeter = eo9(
        &store,
        &["store", "add", &component_arg("hello"), "--name", "greeter"],
    );
    assert_eq!(add_greeter.code, 0, "stderr: {}", add_greeter.stderr);

    let run = eo9(
        &store,
        &["shell", "-c", "greeter --name store --excited false"],
    );
    assert_eq!(run.code, 0, "stderr: {}", run.stderr);
    assert!(run.stdout.contains("Hello, store."), "{}", run.stdout);
    assert!(run.stdout.contains("ok: greeted"), "{}", run.stdout);

    // The session bin view lives under the store root and holds the bound names.
    assert!(store.join("shell/bin/greeter.wasm").is_file());
    assert!(store.join("shell/bin/eosh.wasm").is_file());
}

#[test]
fn shell_env_shows_the_session_capability_picture() {
    // `env` renders the manifest the shell start writes into the session directory:
    // what the shell holds, what children receive, and how to grant more.
    let store = temp_store("shell-env");
    let run = eo9(&store, &["shell", "-c", "env"]);
    assert_eq!(run.code, 0, "stderr: {}", run.stderr);
    assert!(
        run.stdout.contains("capabilities granted to this shell:"),
        "{}",
        run.stdout
    );
    assert!(run.stdout.contains("exec"), "{}", run.stdout);
    assert!(
        run.stdout
            .contains("programs started from this shell receive:"),
        "{}",
        run.stdout
    );
    // Without --fs-root, children get no filesystem and env says how to grant one.
    assert!(run.stdout.contains("--fs-root"), "{}", run.stdout);
    assert!(
        run.stdout.contains("never receive the exec capability"),
        "{}",
        run.stdout
    );
    // The manifest itself sits in the session directory the shell's fs is rooted at.
    assert!(store.join("shell/session").is_file());

    // With --fs-root, the children's filesystem grant (and its root) shows up.
    let fs_root = store.join("data");
    fs::create_dir_all(&fs_root).expect("failed to create the fs root");
    let granted = eo9(
        &store,
        &[
            "shell",
            "--fs-root",
            fs_root.to_str().expect("utf-8 path"),
            "-c",
            "env",
        ],
    );
    assert_eq!(granted.code, 0, "stderr: {}", granted.stderr);
    assert!(
        granted.stdout.contains("host directory") && granted.stdout.contains("(from --fs-root)"),
        "{}",
        granted.stdout
    );
    assert!(
        !granted.stdout.contains("--fs-root <dir> to grant one"),
        "{}",
        granted.stdout
    );
}

#[test]
fn shell_env_of_a_program_marks_imports_against_the_session() {
    let store = temp_store("shell-env-of");

    // hello needs only text, which every session provides.
    let hello = eo9(&store, &["shell", "-c", "env hello"]);
    assert_eq!(hello.code, 0, "stderr: {}", hello.stderr);
    assert!(
        hello.stdout.contains("eo9:text/text@0.1.0"),
        "{}",
        hello.stdout
    );
    assert!(
        hello.stdout.contains("satisfied by the session (text)"),
        "{}",
        hello.stdout
    );
    // Inspecting never runs the program.
    assert!(!hello.stdout.contains("Hello"), "{}", hello.stdout);

    // readwrite requires a filesystem; without --fs-root this session would refuse it.
    let readwrite = eo9(&store, &["shell", "-c", "env readwrite"]);
    assert_eq!(readwrite.code, 0, "stderr: {}", readwrite.stderr);
    assert!(
        readwrite.stdout.contains("eo9:fs/fs@0.1.0"),
        "{}",
        readwrite.stdout
    );
    assert!(
        readwrite
            .stdout
            .contains("missing — would be refused at spawn"),
        "{}",
        readwrite.stdout
    );
}

// -----------------------------------------------------------------------------------
// Store, names, describe
// -----------------------------------------------------------------------------------

#[test]
fn store_add_ls_gc_and_run_by_name() {
    let store = temp_store("store-name");
    let hello = component_arg("hello");

    let added = eo9(&store, &["store", "add", &hello, "--name", "hello"]);
    assert_eq!(added.code, 0, "stderr: {}", added.stderr);
    assert!(
        added.stdout.contains("hello -> "),
        "binding missing from output: {}",
        added.stdout
    );

    let listed = eo9(&store, &["store", "ls"]);
    assert_eq!(listed.code, 0, "stderr: {}", listed.stderr);
    assert!(
        listed.stdout.contains("hello "),
        "ls output: {}",
        listed.stdout
    );
    assert!(
        listed.stdout.contains("objects: 1"),
        "ls output: {}",
        listed.stdout
    );

    // Bare dotted names resolve through the store and run exactly like paths.
    let run = eo9(
        &store,
        &["run", "hello", "--name", "store", "--excited", "false"],
    );
    assert_eq!(run.code, 0, "stderr: {}", run.stderr);
    assert!(
        run.stdout.contains("Hello, store."),
        "stdout: {}",
        run.stdout
    );
    assert_eq!(run.stdout.lines().last(), Some("success(greeted)"));

    let unknown = eo9(&store, &["run", "nosuchname"]);
    assert_eq!(unknown.code, 3);
    assert!(
        unknown.stderr.contains("does not resolve"),
        "unexpected error: {}",
        unknown.stderr
    );

    // gc under the default budget keeps everything and reports what it saw.
    let gc = eo9(&store, &["store", "gc"]);
    assert_eq!(gc.code, 0, "stderr: {}", gc.stderr);
    assert!(
        gc.stdout.starts_with("gc: evicted 0"),
        "gc output: {}",
        gc.stdout
    );

    // gc with a zero budget evicts the cache entry the run created.
    let gc_all = eo9(&store, &["store", "gc", "--max-cache-bytes", "0"]);
    assert_eq!(gc_all.code, 0, "stderr: {}", gc_all.stderr);
    assert!(
        gc_all.stdout.starts_with("gc: evicted 1"),
        "gc output: {}",
        gc_all.stdout
    );
}

#[test]
fn describe_shows_kind_imports_and_arguments() {
    let store = temp_store("describe");
    let hello = component_arg("hello");
    let run = eo9(&store, &["describe", &hello]);
    assert_eq!(run.code, 0, "stderr: {}", run.stderr);
    assert!(run.stdout.contains("kind: binary"), "{}", run.stdout);
    assert!(
        run.stdout.contains("eo9:text/text@0.1.0 (required)"),
        "{}",
        run.stdout
    );
    assert!(
        run.stdout.contains("eo9:time/time@0.1.0 (required)"),
        "{}",
        run.stdout
    );
    assert!(run.stdout.contains("--name <string>"), "{}", run.stdout);
    assert!(run.stdout.contains("--excited <bool>"), "{}", run.stdout);
}

#[test]
fn unknown_commands_and_bad_flags_are_usage_errors() {
    let store = temp_store("usage");
    // Not a subcommand, not an option, not a program reference: still a usage error.
    let unknown = eo9(&store, &["--frobnicate"]);
    assert_eq!(unknown.code, 3);
    assert!(unknown.stderr.contains("unknown command"));

    // A name-shaped first argument is an implicit `run` now; an unbound one fails with
    // the resolver's error rather than "unknown command".
    let unbound = eo9(&store, &["no-such-program"]);
    assert_eq!(unbound.code, 3);
    assert!(
        unbound.stderr.contains("does not resolve"),
        "unexpected error: {}",
        unbound.stderr
    );

    let bad_policy = eo9(&store, &["--exec-snapshot", "maybe", "run", "x.wasm"]);
    assert_eq!(bad_policy.code, 3);
    assert!(bad_policy.stderr.contains("clone-or-refuse"));

    let help = eo9(&store, &["help"]);
    assert_eq!(help.code, 0);
    assert!(help.stdout.contains("USAGE"));
    assert!(help.stdout.contains("DEFAULTS"));
}

// -----------------------------------------------------------------------------------
// Demo defaults: bare invocations and first-run seeding
// -----------------------------------------------------------------------------------

#[test]
fn default_invocations_run_the_shell_and_programs() {
    let store = temp_store("demo-defaults");

    // `eo9 -c "<command>"` is the shell's one-shot form; on a fresh store the first
    // start seeds it from the components embedded in the binary.
    let one_shot = eo9(&store, &["-c", "hello --name demo --excited true"]);
    assert_eq!(one_shot.code, 0, "stderr: {}", one_shot.stderr);
    assert!(
        one_shot.stderr.contains("seeded"),
        "first run should seed the store: {}",
        one_shot.stderr
    );
    assert!(
        one_shot.stdout.contains("Hello, demo!"),
        "{}",
        one_shot.stdout
    );
    assert!(
        one_shot.stdout.contains("ok: greeted"),
        "{}",
        one_shot.stdout
    );

    // `eo9 <path> [--flag value …]` is an implicit `run`.
    let hello = component_arg("hello");
    let by_path = eo9(
        &store,
        &[&hello, "--name", "implicit", "--excited", "false"],
    );
    assert_eq!(by_path.code, 0, "stderr: {}", by_path.stderr);
    assert!(
        by_path.stdout.contains("Hello, implicit."),
        "{}",
        by_path.stdout
    );
    assert_eq!(by_path.stdout.lines().last(), Some("success(greeted)"));

    // And so is `eo9 <bare-name> …` once the name is bound (here: by the seeding above).
    let by_name = eo9(&store, &["hello", "--name", "byname", "--excited", "true"]);
    assert_eq!(by_name.code, 0, "stderr: {}", by_name.stderr);
    assert!(
        by_name.stdout.contains("Hello, byname!"),
        "{}",
        by_name.stdout
    );
}

#[test]
fn first_run_seeding_is_idempotent() {
    let store = temp_store("demo-seed");

    let first = eo9(&store, &["-c", "help"]);
    assert_eq!(first.code, 0, "stderr: {}", first.stderr);
    assert!(
        first.stderr.contains("seeded"),
        "first run should seed: {}",
        first.stderr
    );

    let names = |run: &Run| -> Vec<String> {
        run.stdout
            .lines()
            .skip_while(|line| !line.starts_with("names"))
            .take_while(|line| line.starts_with("names") || line.starts_with("  "))
            .map(str::to_owned)
            .collect()
    };
    let listed = eo9(&store, &["store", "ls"]);
    assert_eq!(listed.code, 0);
    let seeded_names = names(&listed);
    for expected in [
        "hello ",
        "eosh ",
        "cruncher ",
        "entropy.seeded ",
        "fs.memfs ",
    ] {
        assert!(
            seeded_names
                .iter()
                .any(|line| line.trim_start().starts_with(expected)),
            "expected {expected:?} among the seeded names: {seeded_names:?}"
        );
    }

    // A second shell start must not reseed or change any binding.
    let second = eo9(&store, &["-c", "help"]);
    assert_eq!(second.code, 0, "stderr: {}", second.stderr);
    assert!(
        !second.stderr.contains("seeded"),
        "second run must not reseed: {}",
        second.stderr
    );
    let relisted = eo9(&store, &["store", "ls"]);
    assert_eq!(names(&relisted), seeded_names);
}

#[test]
fn seeding_never_clobbers_user_bindings() {
    let store = temp_store("demo-seed-user");

    // The user binds `hello` to the cruncher component before ever starting the shell.
    let added = eo9(
        &store,
        &[
            "store",
            "add",
            &component_arg("cruncher"),
            "--name",
            "hello",
        ],
    );
    assert_eq!(added.code, 0, "stderr: {}", added.stderr);

    // The store is no longer empty, so the shell must not seed and `hello` must still be
    // the user's cruncher (its argument signature gives it away).
    let describe = eo9(&store, &["-c", "describe hello"]);
    assert_eq!(describe.code, 0, "stderr: {}", describe.stderr);
    assert!(
        !describe.stderr.contains("seeded"),
        "a non-empty store must not be seeded: {}",
        describe.stderr
    );
    assert!(
        describe.stdout.contains("--seed: u64"),
        "{}",
        describe.stdout
    );
    assert!(
        !describe.stdout.contains("--name: string"),
        "{}",
        describe.stdout
    );

    let listed = eo9(&store, &["store", "ls"]);
    assert!(listed.stdout.contains("names (1):"), "{}", listed.stdout);
}

// -----------------------------------------------------------------------------------
// coreutils: the basic tool suite (guest/coreutils/*)
// -----------------------------------------------------------------------------------

/// A fresh sandbox directory the shell's children receive as their fs root.
fn temp_sandbox(test: &str) -> PathBuf {
    let dir = Path::new(env!("CARGO_TARGET_TMPDIR")).join(format!("eo9-sandbox-{test}"));
    if dir.exists() {
        fs::remove_dir_all(&dir).expect("failed to clear the sandbox");
    }
    fs::create_dir_all(&dir).expect("failed to create the sandbox");
    dir
}

#[test]
fn coreutils_fs_tools_against_a_sandbox() {
    let store = temp_store("coreutils-fs");
    let sandbox = temp_sandbox("coreutils-fs");
    fs::write(sandbox.join("notes.txt"), "alpha beta\ngamma\n").expect("write fixture");
    let sb = sandbox.to_str().expect("utf-8 sandbox path");

    // ls lists the directory; cat prints contents; wc reports "<lines> <words> <bytes>".
    let ls = eo9(&store, &["--fs-root", sb, "-c", "ls --path /"]);
    assert_eq!(ls.code, 0, "stderr: {}", ls.stderr);
    assert!(ls.stdout.contains("notes.txt"), "ls output: {}", ls.stdout);

    let cat = eo9(&store, &["--fs-root", sb, "-c", "cat --path /notes.txt"]);
    assert_eq!(cat.code, 0, "stderr: {}", cat.stderr);
    assert!(cat.stdout.contains("alpha beta"), "cat output: {}", cat.stdout);

    let wc = eo9(&store, &["--fs-root", sb, "-c", "wc --path /notes.txt"]);
    assert_eq!(wc.code, 0, "stderr: {}", wc.stderr);
    assert!(wc.stdout.contains("2 3 17"), "wc output: {}", wc.stdout);

    // cp copies a file; the copy appears on the host side of the fs root.
    let cp = eo9(
        &store,
        &["--fs-root", sb, "-c", "cp --src /notes.txt --dst /copy.txt"],
    );
    assert_eq!(cp.code, 0, "stderr: {}", cp.stderr);
    assert!(sandbox.join("copy.txt").is_file(), "cp did not create copy.txt");
}

#[test]
fn echo_needs_no_filesystem() {
    // echo imports only eo9:text, so it runs with no fs grant at all.
    let store = temp_store("coreutils-echo");
    let run = eo9(&store, &["-c", "echo --text hello-coreutils"]);
    assert_eq!(run.code, 0, "stderr: {}", run.stderr);
    assert!(run.stdout.contains("hello-coreutils"), "echo output: {}", run.stdout);
}

#[test]
fn rng_with_seeded_entropy_is_deterministic() {
    let store = temp_store("coreutils-rng");
    let values = |run: &Run| -> Vec<String> {
        run.stdout
            .lines()
            .filter(|line| line.parse::<u64>().is_ok())
            .map(str::to_owned)
            .collect()
    };

    // The same seed yields the same draws across runs (rng imports eo9:entropy, which the
    // composed entropy.seeded provider satisfies and seals).
    let a = eo9(&store, &["-c", "entropy.seeded --seed 43 $ rng --count 3"]);
    let b = eo9(&store, &["-c", "entropy.seeded --seed 43 $ rng --count 3"]);
    assert_eq!(a.code, 0, "stderr: {}", a.stderr);
    assert_eq!(b.code, 0, "stderr: {}", b.stderr);
    let va = values(&a);
    assert_eq!(va.len(), 3, "expected three values: {}", a.stdout);
    assert_eq!(va, values(&b), "seeded rng must be deterministic across runs");

    // A different seed changes the output.
    let c = eo9(&store, &["-c", "entropy.seeded --seed 99 $ rng --count 3"]);
    assert_eq!(c.code, 0, "stderr: {}", c.stderr);
    assert_ne!(values(&c), va, "a different seed must change the draws");
}

#[test]
fn fs_coreutil_without_fs_root_is_refused() {
    // A coreutil that requires eo9:fs is refused before running when no fs is granted.
    let store = temp_store("coreutils-no-fs");
    let _ = eo9(&store, &["-c", "help"]); // seed the store so `cat` resolves by name
    let refused = eo9(&store, &["cat", "--path", "/x"]);
    assert_eq!(refused.code, 3, "stderr: {}", refused.stderr);
    assert!(
        refused.stderr.contains("eo9:fs"),
        "expected an fs-capability refusal: {}",
        refused.stderr
    );
}
