//! End-to-end tests of the `eo9` binary against the merged example components
//! (plan/11-usermode.md): `run` of hello / outcomes / cruncher with the three-way
//! outcome and exit codes, compile-cache behaviour on a second run, the memory-limit
//! flag, store-resolved names, `describe`, `compile`, `store` subcommands, and the
//! readwrite end to end through the unix fs provider, and `shell` transcripts (one-shot
//! `-c` commands and a piped interactive session) running eosh against the session view.
//!
//! The tests drive the real binary (`CARGO_BIN_EXE_eo9`) as a subprocess, with the
//! module store pointed at a per-test directory under `CARGO_TARGET_TMPDIR`. Example
//! components are built on demand with `cargo xtask build-guest` if they are missing.

use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;
use std::sync::Once;

const EXAMPLES: &[&str] = &["hello", "outcomes", "cruncher", "readwrite"];

fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../..")
        .canonicalize()
        .expect("repository root must exist")
}

fn component_path(name: &str) -> PathBuf {
    repo_root()
        .join("guest/target/components")
        .join(format!("eo9-example-{name}.wasm"))
}

/// Build the example components (once per test process) if any are missing. When they
/// had to be built, the eo9 binary under test is rebuilt too, so its embedded component
/// set (generated by build.rs from the same directory) is no longer empty.
fn ensure_components() {
    static BUILD: Once = Once::new();
    BUILD.call_once(|| {
        if EXAMPLES.iter().all(|name| component_path(name).exists()) {
            return;
        }
        let status = Command::new("cargo")
            .args(["run", "-p", "xtask", "--", "build-guest"])
            .current_dir(repo_root())
            .status()
            .expect("failed to invoke `cargo run -p xtask -- build-guest`");
        assert!(status.success(), "xtask build-guest failed");

        let status = Command::new("cargo")
            .args(["build", "-p", "eo9"])
            .current_dir(repo_root())
            .status()
            .expect("failed to rebuild the eo9 binary after build-guest");
        assert!(status.success(), "rebuilding eo9 after build-guest failed");
    });
    for name in EXAMPLES {
        assert!(
            component_path(name).exists(),
            "missing example component {}",
            component_path(name).display()
        );
    }
}

/// A fresh store root for one test.
fn temp_store(test: &str) -> PathBuf {
    let dir = Path::new(env!("CARGO_TARGET_TMPDIR")).join(format!("eo9-cli-{test}"));
    if dir.exists() {
        fs::remove_dir_all(&dir).expect("failed to clear the test store");
    }
    fs::create_dir_all(&dir).expect("failed to create the test store");
    dir
}

struct Run {
    code: i32,
    stdout: String,
    stderr: String,
}

/// Run the eo9 binary with `args`, using `store` as the module store root.
fn eo9(store: &Path, args: &[&str]) -> Run {
    eo9_with_stdin(store, args, None)
}

/// Run the eo9 binary, optionally feeding `stdin` (used for interactive-shell
/// transcripts; the text provider reads the piped stream like any stdin).
fn eo9_with_stdin(store: &Path, args: &[&str], stdin: Option<&str>) -> Run {
    use std::io::Write as _;
    use std::process::Stdio;

    ensure_components();
    let mut command = Command::new(env!("CARGO_BIN_EXE_eo9"));
    command
        .args(args)
        .env("EO9_STORE", store)
        .current_dir(repo_root())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .stdin(if stdin.is_some() {
            Stdio::piped()
        } else {
            Stdio::null()
        });
    let mut child = command.spawn().expect("failed to start the eo9 binary");
    if let Some(script) = stdin {
        child
            .stdin
            .take()
            .expect("stdin was piped")
            .write_all(script.as_bytes())
            .expect("failed to write the shell transcript");
    }
    let output = child
        .wait_with_output()
        .expect("failed to run the eo9 binary");
    Run {
        code: output.status.code().expect("eo9 exited without a code"),
        stdout: String::from_utf8_lossy(&output.stdout).into_owned(),
        stderr: String::from_utf8_lossy(&output.stderr).into_owned(),
    }
}

fn component_arg(name: &str) -> String {
    component_path(name)
        .to_str()
        .expect("utf-8 path")
        .to_owned()
}

// -----------------------------------------------------------------------------------
// run: the example binaries end to end
// -----------------------------------------------------------------------------------

#[test]
fn run_hello_by_path_end_to_end() {
    let store = temp_store("run-hello");
    let hello = component_arg("hello");
    let run = eo9(
        &store,
        &["run", &hello, "--name", "eo9", "--excited", "true"],
    );
    assert_eq!(run.code, 0, "stderr: {}", run.stderr);
    assert!(
        run.stdout.contains("Hello, eo9!"),
        "program output missing from stdout: {}",
        run.stdout
    );
    assert_eq!(
        run.stderr.lines().last(),
        Some("success(greeted)"),
        "outcome line missing from stderr: {}",
        run.stderr
    );
}

#[test]
fn run_outcomes_covers_success_failure_and_abnormal() {
    let store = temp_store("run-outcomes");
    let outcomes = component_arg("outcomes");
    let run_mode = |mode: &str, detail: &str| {
        eo9(
            &store,
            &["run", &outcomes, "--mode", mode, "--detail", detail],
        )
    };

    let ok = run_mode("ok", "all good");
    assert_eq!(ok.code, 0, "stderr: {}", ok.stderr);
    assert_eq!(
        ok.stderr.lines().last(),
        Some("success(completed(\"all good\"))")
    );

    let quiet = run_mode("quiet", "");
    assert_eq!(quiet.code, 0, "stderr: {}", quiet.stderr);
    assert_eq!(quiet.stderr.trim(), "success(quiet)");

    let fail = run_mode("fail", "went wrong");
    assert_eq!(fail.code, 1, "stderr: {}", fail.stderr);
    assert_eq!(
        fail.stderr.lines().last(),
        Some("failure(requested-failure(\"went wrong\"))")
    );

    let rejected = run_mode("nonsense", "");
    assert_eq!(rejected.code, 1, "stderr: {}", rejected.stderr);
    assert!(
        rejected.stderr.trim().starts_with("failure(bad-arguments("),
        "unexpected outcome: {}",
        rejected.stderr
    );

    // A guest panic lowers to a wasm trap: the executor's abnormal arm, exit code 2.
    let trapped = run_mode("trap", "");
    assert_eq!(trapped.code, 2, "stderr: {}", trapped.stderr);
    assert!(
        trapped.stderr.trim().starts_with("abnormal(trapped("),
        "unexpected outcome: {}",
        trapped.stderr
    );
    assert!(
        trapped.stderr.contains("unreachable"),
        "trap reason missing: {}",
        trapped.stderr
    );
    // The reason is the cleaned, deterministic form: a panic label, the trap kind, and a
    // symbol-only backtrace naming the panicking function — with no code addresses or
    // rustc `[hash]` disambiguators (the raw `{err:#}` noise the user studies flagged).
    assert!(
        trapped.stderr.contains("guest panicked"),
        "trap reason should be labelled a guest panic: {}",
        trapped.stderr
    );
    // The guest's own panic message and source location lead the reason: the SDK panic
    // handler reports them through `eo9:rt/diagnostics.report-panic` just before the
    // trap, and the executor folds them into `trapped(reason)`.
    assert!(
        trapped
            .stderr
            .contains("guest panicked: outcomes: trapping as requested at "),
        "trap reason should carry the panic message: {}",
        trapped.stderr
    );
    assert!(
        trapped.stderr.contains("lib.rs:"),
        "trap reason should carry the panic source location: {}",
        trapped.stderr
    );
    assert!(
        trapped.stderr.contains("guest backtrace:") && trapped.stderr.contains("main"),
        "trap reason should name the panicking function: {}",
        trapped.stderr
    );
    assert!(
        !trapped.stderr.contains("0x") && !trapped.stderr.contains('['),
        "trap reason should carry no addresses or [hash] noise: {}",
        trapped.stderr
    );
}

#[test]
fn run_cruncher_is_deterministic_pure_compute() {
    let store = temp_store("run-cruncher");
    let cruncher = component_arg("cruncher");

    // The same splitmix64 mix as the example, so the digest can be checked exactly.
    fn mix(state: u64) -> u64 {
        let mut z = state.wrapping_add(0x9e37_79b9_7f4a_7c15);
        z = (z ^ (z >> 30)).wrapping_mul(0xbf58_476d_1ce4_e5b9);
        z = (z ^ (z >> 27)).wrapping_mul(0x94d0_49bb_1331_11eb);
        z ^ (z >> 31)
    }
    let expected = (0..1000).fold(9u64, |digest, _| mix(digest));

    let first = eo9(
        &store,
        &["run", &cruncher, "--seed", "9", "--rounds", "1000"],
    );
    assert_eq!(first.code, 0, "stderr: {}", first.stderr);
    assert_eq!(first.stderr.trim(), format!("success(digest({expected}))"));

    // Pure compute with fixed arguments is bit-deterministic run to run.
    let second = eo9(
        &store,
        &["run", &cruncher, "--seed", "9", "--rounds", "1000"],
    );
    assert_eq!(second.code, 0, "stderr: {}", second.stderr);
    assert_eq!(second.stderr, first.stderr);

    // Zero rounds is rejected in the program's own failure vocabulary.
    let rejected = eo9(&store, &["run", &cruncher, "--seed", "9", "--rounds", "0"]);
    assert_eq!(rejected.code, 1);
    assert!(rejected.stderr.trim().starts_with("failure(bad-arguments("));
}

// -----------------------------------------------------------------------------------
// Compile cache
// -----------------------------------------------------------------------------------

#[test]
fn second_run_launches_from_the_cached_image() {
    let store = temp_store("cache-hit");
    let cruncher = component_arg("cruncher");
    let args = ["-v", "run", &cruncher, "--seed", "1", "--rounds", "10"];

    let first = eo9(&store, &args);
    assert_eq!(first.code, 0, "stderr: {}", first.stderr);
    assert!(
        first.stderr.contains("compile cache miss"),
        "first run should miss: {}",
        first.stderr
    );
    assert!(
        first.stderr.contains("cached image"),
        "first run should cache the image it compiled: {}",
        first.stderr
    );

    // The second run takes the cached path: it deserializes the stored image and never
    // reaches codegen (no "compiling"/"compiled" diagnostics), yet the outcome is
    // identical.
    let second = eo9(&store, &args);
    assert_eq!(second.code, 0, "stderr: {}", second.stderr);
    assert!(
        second.stderr.contains("launched from cached image"),
        "second run should launch from the cache: {}",
        second.stderr
    );
    assert!(
        !second.stderr.contains("compiling") && !second.stderr.contains("compiled"),
        "second run must not pay codegen: {}",
        second.stderr
    );
    assert_eq!(second.stdout, first.stdout);

    // The store's cache entry records both uses (insert counts as the first).
    let cache_dir = store.join("cache");
    let mut use_counts = Vec::new();
    for entry in fs::read_dir(&cache_dir).expect("cache directory must exist") {
        let meta = entry.expect("readable cache entry").path().join("meta");
        let text = fs::read_to_string(meta).expect("readable cache metadata");
        let count = text
            .lines()
            .find_map(|line| line.strip_prefix("use-count "))
            .expect("metadata carries a use-count")
            .parse::<u64>()
            .expect("use-count is a number");
        use_counts.push(count);
    }
    assert_eq!(
        use_counts,
        vec![2],
        "unexpected cache usage: {use_counts:?}"
    );
}

#[test]
fn corrupted_cache_entries_are_ignored_not_trusted() {
    let store = temp_store("cache-corrupt");
    let cruncher = component_arg("cruncher");
    let args = ["-v", "run", &cruncher, "--seed", "3", "--rounds", "10"];

    let first = eo9(&store, &args);
    assert_eq!(first.code, 0, "stderr: {}", first.stderr);

    // Flip the last byte of the cached artifact: the envelope's recorded content hash no
    // longer matches, so the entry must be refused and the component recompiled.
    let cache_dir = store.join("cache");
    let entry = fs::read_dir(&cache_dir)
        .expect("cache directory must exist")
        .next()
        .expect("one cache entry")
        .expect("readable cache entry");
    let image_path = entry.path().join("image");
    let mut bytes = fs::read(&image_path).expect("readable cached image");
    let last = bytes.len() - 1;
    bytes[last] ^= 0x01;
    fs::write(&image_path, &bytes).expect("cached image is writable in the test store");

    let second = eo9(&store, &args);
    assert_eq!(second.code, 0, "stderr: {}", second.stderr);
    assert!(
        second.stderr.contains("ignoring compile-cache entry"),
        "the tampered entry should be refused: {}",
        second.stderr
    );
    assert!(
        !second.stderr.contains("launched from cached image"),
        "the tampered entry must not be launched: {}",
        second.stderr
    );
    assert_eq!(second.stdout, first.stdout);
}

#[test]
fn an_unwritable_cache_never_fails_a_run() {
    use std::os::unix::fs::PermissionsExt;

    fn set_mode(path: &Path, mode: u32) {
        fs::set_permissions(path, fs::Permissions::from_mode(mode))
            .unwrap_or_else(|err| panic!("cannot chmod {}: {err}", path.display()));
    }

    let store = temp_store("cache-readonly");
    let cruncher = component_arg("cruncher");
    let args = ["-v", "run", &cruncher, "--seed", "5", "--rounds", "10"];

    // Cold cache, read-only cache directory: the insert after compiling fails, the run
    // still succeeds with a warning.
    let cache_dir = store.join("cache");
    fs::create_dir_all(&cache_dir).expect("create the cache directory");
    set_mode(&cache_dir, 0o555);
    let cold = eo9(&store, &args);
    set_mode(&cache_dir, 0o755);
    assert_eq!(cold.code, 0, "stderr: {}", cold.stderr);
    assert!(
        cold.stderr.contains("could not be cached"),
        "expected an insert warning: {}",
        cold.stderr
    );
    assert!(
        cold.stderr
            .lines()
            .last()
            .unwrap_or("")
            .starts_with("success(digest("),
        "outcome line missing from stderr: {}",
        cold.stderr
    );

    // Populate the cache normally, then make the entry read-only: the lookup's
    // use-count bump fails, which is treated as a miss (warn + recompile), not an error.
    let warm = eo9(&store, &args);
    assert_eq!(warm.code, 0, "stderr: {}", warm.stderr);
    let entry_dir = fs::read_dir(&cache_dir)
        .expect("cache directory must exist")
        .next()
        .expect("one cache entry")
        .expect("readable cache entry")
        .path();
    set_mode(&entry_dir, 0o555);
    let bumped = eo9(&store, &args);
    set_mode(&entry_dir, 0o755);
    assert_eq!(bumped.code, 0, "stderr: {}", bumped.stderr);
    assert!(
        bumped.stderr.contains("compile-cache lookup failed"),
        "expected a lookup warning: {}",
        bumped.stderr
    );
    assert_eq!(bumped.stdout, cold.stdout);
}

#[test]
fn compile_warms_the_cache_for_a_later_run() {
    let store = temp_store("compile-warm");
    let outcomes = component_arg("outcomes");

    let warm = eo9(&store, &["compile", &outcomes]);
    assert_eq!(warm.code, 0, "stderr: {}", warm.stderr);
    assert!(
        warm.stdout.starts_with("compiled and cached:"),
        "unexpected compile output: {}",
        warm.stdout
    );

    let run = eo9(
        &store,
        &["-v", "run", &outcomes, "--mode", "quiet", "--detail", ""],
    );
    assert_eq!(run.code, 0, "stderr: {}", run.stderr);
    assert!(
        run.stderr.contains("launched from cached image"),
        "run after warm should launch from the cache: {}",
        run.stderr
    );

    let rewarm = eo9(&store, &["compile", &outcomes]);
    assert_eq!(rewarm.code, 0);
    assert!(rewarm.stdout.starts_with("compile cache hit:"));
}

// -----------------------------------------------------------------------------------
// Limits and refusal paths
// -----------------------------------------------------------------------------------

#[test]
fn memory_limit_flag_is_enforced() {
    let store = temp_store("memory-limit");
    let cruncher = component_arg("cruncher");

    // Far below the component's initial linear memory: the limiter refuses the very
    // first allocation and the spawn fails before any guest code runs.
    let denied = eo9(
        &store,
        &[
            "--max-memory",
            "65536",
            "run",
            &cruncher,
            "--seed",
            "1",
            "--rounds",
            "10",
        ],
    );
    assert_eq!(denied.code, 3, "stdout: {}", denied.stdout);
    assert!(
        denied.stderr.contains("memory"),
        "expected a memory-limit spawn error: {}",
        denied.stderr
    );

    // A generous ceiling changes nothing about a well-behaved program.
    let allowed = eo9(
        &store,
        &[
            "--max-memory",
            "67108864",
            "run",
            &cruncher,
            "--seed",
            "1",
            "--rounds",
            "10",
        ],
    );
    assert_eq!(allowed.code, 0, "stderr: {}", allowed.stderr);
}

#[test]
fn readwrite_round_trips_through_the_unix_fs() {
    // The async fs example end to end from the CLI: the program's eo9:fs capability is
    // the unix fs provider rooted at --fs-root, the owned-buffer write/read round-trip
    // goes through real host files, and the outcome is the program's own success value.
    let store = temp_store("readwrite");
    let fs_root = temp_store("readwrite-fsroot");
    let readwrite = component_arg("readwrite");
    let run = eo9(
        &store,
        &[
            "--fs-root",
            fs_root.to_str().expect("utf-8 fs root"),
            "run",
            &readwrite,
            "--path",
            "note.txt",
            "--contents",
            "hello disk",
        ],
    );
    assert_eq!(run.code, 0, "stderr: {}", run.stderr);
    assert_eq!(run.stderr.trim(), "success(round-tripped(10))");

    // The write really landed on the host filesystem, under the fs root.
    assert_eq!(
        fs::read_to_string(fs_root.join("note.txt")).expect("note.txt exists under the fs root"),
        "hello disk"
    );
}

#[test]
fn readwrite_failures_stay_in_the_programs_vocabulary_and_inside_the_root() {
    let store = temp_store("readwrite-fail");
    let fs_root = temp_store("readwrite-fail-fsroot");
    let readwrite = component_arg("readwrite");
    let run_with_path = |path: &str| {
        eo9(
            &store,
            &[
                "--fs-root",
                fs_root.to_str().expect("utf-8 fs root"),
                "run",
                &readwrite,
                "--path",
                path,
                "--contents",
                "should not land",
            ],
        )
    };

    // A path that tries to climb out of the fs root is refused by the provider's
    // containment and surfaces as the program's own fs(...) failure case.
    let escape = run_with_path("../escaped.txt");
    assert_eq!(escape.code, 1, "stderr: {}", escape.stderr);
    assert!(
        escape.stderr.trim().starts_with("failure(fs("),
        "expected the program's fs failure: {}",
        escape.stderr
    );
    assert!(
        escape.stderr.contains("Denied"),
        "expected a denied error: {}",
        escape.stderr
    );
    assert!(
        !fs_root
            .parent()
            .expect("fs root has a parent")
            .join("escaped.txt")
            .exists(),
        "nothing may be created outside the fs root"
    );

    // Opening inside a directory that does not exist fails through the provider and is
    // reported the same way (not-found, in the program's vocabulary).
    let missing = run_with_path("no-such-dir/note.txt");
    assert_eq!(missing.code, 1, "stderr: {}", missing.stderr);
    assert!(
        missing.stderr.trim().starts_with("failure(fs("),
        "expected the program's fs failure: {}",
        missing.stderr
    );
}

#[test]
fn fs_is_not_granted_without_an_explicit_fs_root() {
    // No ambient filesystem authority: without --fs-root there is no fs provider at all,
    // and a program that requires eo9:fs is refused before it runs, with a hint that
    // names the flag.
    let store = temp_store("readwrite-no-grant");
    let readwrite = component_arg("readwrite");
    let run = eo9(
        &store,
        &[
            "run",
            &readwrite,
            "--path",
            "note.txt",
            "--contents",
            "should never land",
        ],
    );
    assert_eq!(run.code, 3, "stdout: {}", run.stdout);
    assert!(
        run.stderr.contains("--fs-root"),
        "the refusal should point at --fs-root: {}",
        run.stderr
    );
    assert!(
        run.stderr.contains("eo9:fs"),
        "the refusal should name the missing capability: {}",
        run.stderr
    );
    // And nothing was written anywhere (the repo root is eo9's cwd in these tests).
    assert!(!repo_root().join("note.txt").exists());
}

#[test]
fn missing_arguments_are_a_spawn_error() {
    let store = temp_store("missing-args");
    let hello = component_arg("hello");
    let run = eo9(&store, &["run", &hello, "--name", "eo9"]);
    assert_eq!(run.code, 3, "stdout: {}", run.stdout);
    assert!(
        run.stderr.contains("missing argument `excited`"),
        "unexpected error: {}",
        run.stderr
    );
}

// -----------------------------------------------------------------------------------
// The shell (eosh running under `eo9 shell`)
// -----------------------------------------------------------------------------------

#[test]
fn shell_runs_a_program_by_bare_name() {
    // One-shot mode: eosh resolves `hello` as /bin/hello.wasm on the session fs (seeded
    // from the dev-tree components here), composes nothing, compiles, spawns it as a
    // child with the session root providers, and renders the child's own outcome.
    let store = temp_store("shell-hello");
    let run = eo9(
        &store,
        &["shell", "-c", "hello --name shell --excited true"],
    );
    assert_eq!(run.code, 0, "stderr: {}", run.stderr);
    assert!(run.stdout.contains("Hello, shell!"), "{}", run.stdout);
    // The program's output is on stdout; the per-command outcome line is on stderr in
    // one-shot mode (so `-c` pipes carry only program output, like `eo9 run`).
    assert!(run.stderr.contains("ok: greeted"), "{}", run.stderr);
    assert!(!run.stdout.contains("ok: greeted"), "{}", run.stdout);
}

#[test]
fn shell_verbose_announces_child_grants() {
    // `-v` makes the capability set children inherit visible at spawn time (user-study
    // finding #8); a default run stays quiet (the full picture is still in `env`).
    let store = temp_store("shell-vgrants");
    let verbose = eo9(
        &store,
        &["-v", "shell", "-c", "hello --name v --excited true"],
    );
    assert_eq!(verbose.code, 0, "stderr: {}", verbose.stderr);
    assert!(
        verbose
            .stderr
            .contains("children spawned from this shell inherit"),
        "verbose run should announce child grants: {}",
        verbose.stderr
    );
    let quiet = eo9(&store, &["shell", "-c", "hello --name v --excited true"]);
    assert!(
        !quiet
            .stderr
            .contains("children spawned from this shell inherit"),
        "non-verbose run should stay quiet: {}",
        quiet.stderr
    );
}

#[test]
fn shell_describe_builtin_inspects_without_running() {
    let store = temp_store("shell-describe");
    let run = eo9(&store, &["shell", "-c", "describe hello"]);
    assert_eq!(run.code, 0, "stderr: {}", run.stderr);
    assert!(run.stdout.contains("kind: binary"), "{}", run.stdout);
    assert!(run.stdout.contains("--name: string"), "{}", run.stdout);
    assert!(run.stdout.contains("eo9:text/text"), "{}", run.stdout);
    // A plain reference is a single wiring leaf.
    assert!(run.stdout.contains("wiring:"), "{}", run.stdout);
    // Describing does not run the program.
    assert!(!run.stdout.contains("Hello"), "{}", run.stdout);
}

#[test]
fn shell_describe_builtin_shows_the_composition_tree() {
    // `describe` of an expression eosh composed shows the wiring tree (the eosh-side
    // counterpart of `eo9 describe --wiring`): the `$` node with its provider and
    // consumer leaves, fetched through `eo9:exec`'s `wiring`.
    let store = temp_store("shell-describe-wiring");
    let run = eo9(
        &store,
        &["shell", "-c", "describe entropy.seeded $ cruncher"],
    );
    assert_eq!(run.code, 0, "stderr: {}", run.stderr);
    assert!(run.stdout.contains("wiring:"), "{}", run.stdout);
    assert!(run.stdout.contains("$ compose"), "{}", run.stdout);
    assert!(run.stdout.contains("provider:"), "{}", run.stdout);
    assert!(run.stdout.contains("consumer:"), "{}", run.stdout);
    // Describing does not compile or run the composition.
    assert!(!run.stdout.contains("digest("), "{}", run.stdout);
}

#[test]
fn shell_composes_with_the_algebra() {
    // An (unconfigured) provider composed onto a pure-compute binary: `$` goes through
    // eosh's algebra imports, the result compiles and runs, and the digest matches what
    // the same seed produces under `eo9 run` (composition with an unused provider is the
    // identity on behaviour).
    let store = temp_store("shell-compose");
    let run = eo9(
        &store,
        &[
            "shell",
            "-c",
            "entropy.seeded $ cruncher --seed 3 --rounds 100",
        ],
    );
    assert_eq!(run.code, 0, "stderr: {}", run.stderr);
    assert!(run.stderr.contains("ok: digest("), "{}", run.stderr);

    let direct = eo9(
        &store,
        &[
            "run",
            &component_arg("cruncher"),
            "--seed",
            "3",
            "--rounds",
            "100",
        ],
    );
    let digest = |text: &str| {
        text.lines()
            .find_map(|line| {
                let start = line.find("digest(")?;
                line[start..]
                    .strip_prefix("digest(")?
                    .split(')')
                    .next()
                    .map(str::to_owned)
            })
            .expect("a digest in the output")
    };
    assert_eq!(digest(&run.stderr), digest(&direct.stderr));
}

#[test]
fn shell_maps_child_outcomes_to_honest_exit_codes() {
    // `-c` follows `eo9 run`'s contract: 1 the command reported failure, 2 it ended
    // abnormally, 3 the shell could not run it at all. eosh's `program-failure` carries
    // the inner command's class (plan/11 D14/D16), so the embedder no longer collapses
    // everything to 1.
    let store = temp_store("shell-fail");
    let failed = eo9(
        &store,
        &["shell", "-c", "outcomes --mode fail --detail boom"],
    );
    assert_eq!(failed.code, 1, "stdout: {}", failed.stdout);
    // eosh surfaces the command's own outcome on stderr; the exit code (1) carries the
    // failure. The embedder no longer re-prints a redundant `failure(command-failed(…))`
    // wrapper "one layer down" (a user-study finding).
    assert!(
        failed.stderr.contains("error: requested-failure(\"boom\")"),
        "{}",
        failed.stderr
    );
    assert!(
        !failed.stderr.contains("command-failed"),
        "the redundant command-failed wrapper should not be re-printed: {}",
        failed.stderr
    );

    // The inner command trapping is the abnormal class — exit 2, like `eo9 run`.
    let trapped = eo9(
        &store,
        &["shell", "-c", "outcomes --mode trap --detail ignored"],
    );
    assert_eq!(trapped.code, 2, "stdout: {}", trapped.stdout);
    assert!(
        trapped.stderr.contains("abnormal: trapped"),
        "{}",
        trapped.stderr
    );

    // A command eosh could not run at all (nothing was spawned) is an eosh-level error —
    // exit 3, distinct from "the command failed".
    let unknown = eo9(&store, &["shell", "-c", "nosuchprogram"]);
    assert_eq!(unknown.code, 3, "stdout: {}", unknown.stdout);
    assert!(
        unknown.stderr.contains("cannot resolve `nosuchprogram`"),
        "{}",
        unknown.stderr
    );
}

#[test]
fn shell_interactive_transcript_with_let_bindings() {
    // Interactive mode over a piped stdin (no TTY needed): a `let` binding, a use of it
    // with flags, and a clean exit.
    let store = temp_store("shell-interactive");
    let run = eo9_with_stdin(
        &store,
        &["shell"],
        Some("let h = hello\nh --name fromlet --excited true\nexit\n"),
    );
    assert_eq!(run.code, 0, "stderr: {}", run.stderr);
    assert!(run.stdout.contains("eosh>"), "{}", run.stdout);
    assert!(run.stdout.contains("Hello, fromlet!"), "{}", run.stdout);
    assert!(run.stdout.contains("ok: greeted"), "{}", run.stdout);
}

/// Regression test for the duplicated interactive prompt: pressing Enter on a line that
/// produces no stdout (an empty line, a parse error) must not make the next repaint show
/// `eosh> eosh> …`. The interactive path needs a real terminal, so the shell is run
/// inside a pseudo-terminal via script(1); the BSD invocation used here is macOS-only
/// (which is also the only place `cargo xtask ci` runs today).
#[test]
#[cfg(target_os = "macos")]
fn shell_interactive_pty_prompt_is_not_duplicated() {
    use std::io::Write as _;
    use std::process::Stdio;
    use std::time::Duration;

    ensure_components();
    let store = temp_store("shell-pty-prompt");

    // Warm the store seeding and the eosh compile cache first (no pty), so the pty
    // session below reaches its first interactive read quickly and the paced input
    // arrives after the editor owns the terminal.
    let warm = eo9(&store, &["shell", "-c", "help"]);
    assert_eq!(warm.code, 0, "stderr: {}", warm.stderr);

    let mut child = Command::new("/usr/bin/script")
        .args(["-q", "/dev/null", env!("CARGO_BIN_EXE_eo9"), "shell"])
        .env("EO9_STORE", &store)
        .current_dir(repo_root())
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .expect("failed to start script(1) with the eo9 shell");

    // Paced keystrokes: empty Enters, a command with output, a parse error (stderr
    // only), then exit. The pauses keep each line's processing apart; exact timing is
    // not load-bearing for the assertion (a duplicate would persist in the repaints).
    {
        let stdin = child.stdin.as_mut().expect("stdin was piped");
        let mut send = |bytes: &[u8], wait_ms: u64| {
            stdin.write_all(bytes).expect("write to the pty");
            stdin.flush().expect("flush the pty");
            std::thread::sleep(Duration::from_millis(wait_ms));
        };
        std::thread::sleep(Duration::from_millis(1500));
        send(b"\r", 400);
        send(b"\r", 400);
        send(b"hello --name pty --excited true\r", 1500);
        send(b"\r", 400);
        send(b"badsyntax )\r", 600);
        send(b"exit\r", 600);
    }
    drop(child.stdin.take());

    let output = child
        .wait_with_output()
        .expect("script(1) session did not finish");
    let stdout = String::from_utf8_lossy(&output.stdout).into_owned();

    // The interactive editor ran (prompt repaints use clear-line escapes)…
    assert!(stdout.contains("eosh>"), "no prompt seen: {stdout:?}");
    assert!(
        stdout.contains("\u{1b}[2K"),
        "the interactive editor did not run (no repaints): {stdout:?}"
    );
    // …and no repaint ever stacked one prompt onto another.
    assert!(
        !stdout.contains("eosh> eosh>"),
        "duplicated prompt in the interactive session: {stdout:?}"
    );
}

#[test]
fn shell_resolves_store_bound_names_and_eosh_from_the_store() {
    // Bind eosh and a program under a name that exists only in the store: the session
    // bin view must come from the store bindings (hardlinks to store objects), not from
    // the dev tree, and eosh itself must be found via its store binding.
    let store = temp_store("shell-store-names");
    let add_eosh = eo9(
        &store,
        &[
            "store",
            "add",
            &component_path("hello")
                .with_file_name("eosh.wasm")
                .display()
                .to_string(),
            "--name",
            "eosh",
        ],
    );
    assert_eq!(add_eosh.code, 0, "stderr: {}", add_eosh.stderr);
    let add_greeter = eo9(
        &store,
        &["store", "add", &component_arg("hello"), "--name", "greeter"],
    );
    assert_eq!(add_greeter.code, 0, "stderr: {}", add_greeter.stderr);

    let run = eo9(
        &store,
        &["shell", "-c", "greeter --name store --excited false"],
    );
    assert_eq!(run.code, 0, "stderr: {}", run.stderr);
    assert!(run.stdout.contains("Hello, store."), "{}", run.stdout);
    assert!(run.stderr.contains("ok: greeted"), "{}", run.stderr);

    // The session bin view lives under the store root and holds the bound names.
    assert!(store.join("shell/bin/greeter.wasm").is_file());
    assert!(store.join("shell/bin/eosh.wasm").is_file());
}

#[test]
fn shell_env_shows_the_session_capability_picture() {
    // `env` renders the manifest the shell start writes into the session directory:
    // what the shell holds, what children receive, and how to grant more.
    let store = temp_store("shell-env");
    let run = eo9(&store, &["shell", "-c", "env"]);
    assert_eq!(run.code, 0, "stderr: {}", run.stderr);
    assert!(
        run.stdout.contains("capabilities granted to this shell:"),
        "{}",
        run.stdout
    );
    assert!(run.stdout.contains("exec"), "{}", run.stdout);
    assert!(
        run.stdout
            .contains("programs started from this shell receive:"),
        "{}",
        run.stdout
    );
    // Children inherit the full environment (including exec); the note points at `only`
    // as the way to restrict a command, and — without --fs-root — at how to grant a
    // writable data root.
    assert!(run.stdout.contains("--fs-root"), "{}", run.stdout);
    assert!(
        run.stdout.contains("restrict a command with `only`"),
        "{}",
        run.stdout
    );
    assert!(
        !run.stdout.contains("never receive the exec capability"),
        "{}",
        run.stdout
    );
    // The manifest itself sits in the session directory the shell's fs is rooted at.
    assert!(store.join("shell/session").is_file());

    // With --fs-root, the children's filesystem grant (and its root) shows up.
    let fs_root = store.join("data");
    fs::create_dir_all(&fs_root).expect("failed to create the fs root");
    let granted = eo9(
        &store,
        &[
            "shell",
            "--fs-root",
            fs_root.to_str().expect("utf-8 path"),
            "-c",
            "env",
        ],
    );
    assert_eq!(granted.code, 0, "stderr: {}", granted.stderr);
    assert!(
        granted.stdout.contains("host directory") && granted.stdout.contains("(from --fs-root)"),
        "{}",
        granted.stdout
    );
    assert!(
        !granted
            .stdout
            .contains("to give programs a writable data directory"),
        "{}",
        granted.stdout
    );
}

#[test]
fn shell_env_of_a_program_marks_imports_against_the_session() {
    let store = temp_store("shell-env-of");

    // hello needs only text, which every session provides.
    let hello = eo9(&store, &["shell", "-c", "env hello"]);
    assert_eq!(hello.code, 0, "stderr: {}", hello.stderr);
    assert!(
        hello.stdout.contains("eo9:text/text@0.1.0"),
        "{}",
        hello.stdout
    );
    assert!(
        hello.stdout.contains("satisfied by the session (text)"),
        "{}",
        hello.stdout
    );
    // Inspecting never runs the program.
    assert!(!hello.stdout.contains("Hello"), "{}", hello.stdout);

    // readwrite requires a filesystem; the session always layers one (the read-only /bin
    // program view, writable only when --fs-root adds a data root), so the import is
    // satisfied — `env` reports the grant rather than a refusal.
    let readwrite = eo9(&store, &["shell", "-c", "env readwrite"]);
    assert_eq!(readwrite.code, 0, "stderr: {}", readwrite.stderr);
    assert!(
        readwrite.stdout.contains("eo9:fs/fs@0.1.0"),
        "{}",
        readwrite.stdout
    );
    assert!(
        readwrite.stdout.contains("satisfied by the session (fs)"),
        "{}",
        readwrite.stdout
    );
}

#[test]
fn shell_child_inherits_the_full_exec_environment_and_recurses() {
    // The headline of the child-capability default: a child `eosh` launched from `eosh`
    // is a full peer — it inherits the whole `eo9:exec` surface (component algebra,
    // compile, spawn) plus the layered session filesystem, so it can both spawn programs
    // AND compose them, and it can recurse. Driven through piped stdin: the nested shell
    // consumes the rest of the script and EOF ends both shells (a nested non-tty shell
    // shares the one stdin, so every command goes before the implicit exits).
    let store = temp_store("shell-recurse");
    let script = "eosh\n\
                  hello --name nested --excited true\n\
                  only eo9:text/text,eo9:time/time $ hello --name boxed --excited true\n\
                  text.null $ hello --name quiet --excited true\n";
    let run = eo9_with_stdin(&store, &["shell"], Some(script));
    assert_eq!(run.code, 0, "stderr: {}", run.stderr);

    // Two banners: the outer shell launched a nested one (recursion).
    let banners = run.stdout.matches("eosh — the Eo9 shell").count();
    assert!(
        banners >= 2,
        "expected a nested shell banner: {}",
        run.stdout
    );
    // The nested shell SPAWNED a program.
    assert!(
        run.stdout.contains("Hello, nested!"),
        "nested shell did not run a program: {}",
        run.stdout
    );
    // The nested shell COMPOSED with `only` and ran the result.
    assert!(
        run.stdout.contains("Hello, boxed!"),
        "nested shell could not compose with `only`: {}",
        run.stdout
    );
    // The nested shell COMPOSED with `$`: text.null seals hello's text, so the greeting
    // is discarded but the program still succeeds.
    assert!(
        !run.stdout.contains("Hello, quiet!"),
        "text.null should have sealed the greeting: {}",
        run.stdout
    );
    assert!(
        run.stdout.contains("greeted"),
        "expected a success outcome from the nested shell: {}",
        run.stdout
    );
}

#[test]
fn shell_children_see_bin_programs_and_fs_root_data_at_once() {
    // The layered session filesystem: a data tool sees the user's --fs-root files at `/`
    // AND the read-only /bin program view, in one capability. Writes land in the data
    // root and never touch the program view.
    let store = temp_store("shell-overlay");
    let sandbox = temp_sandbox("shell-overlay");
    fs::write(sandbox.join("notes.txt"), "layered\n").expect("write fixture");
    let sb = sandbox.to_str().expect("utf-8 sandbox path");

    // `ls` with no arguments lists the root (the variadic tail defaults to empty).
    let ls = eo9(&store, &["--fs-root", sb, "-c", "ls"]);
    assert_eq!(ls.code, 0, "stderr: {}", ls.stderr);
    assert!(ls.stdout.contains("notes.txt"), "ls output: {}", ls.stdout);
    assert!(ls.stdout.contains("bin"), "ls output: {}", ls.stdout);

    let ls_bin = eo9(&store, &["--fs-root", sb, "-c", "ls /bin"]);
    assert_eq!(ls_bin.code, 0, "stderr: {}", ls_bin.stderr);
    assert!(
        ls_bin.stdout.contains("hello.wasm"),
        "ls /bin output: {}",
        ls_bin.stdout
    );

    let cat = eo9(&store, &["--fs-root", sb, "-c", "cat /notes.txt"]);
    assert_eq!(cat.code, 0, "stderr: {}", cat.stderr);
    assert!(cat.stdout.contains("layered"), "cat output: {}", cat.stdout);

    // A write goes to the data root on the host side, not into the program view.
    let cp = eo9(
        &store,
        &["--fs-root", sb, "-c", "cp --src /notes.txt --dst /copy.txt"],
    );
    assert_eq!(cp.code, 0, "stderr: {}", cp.stderr);
    assert!(sandbox.join("copy.txt").is_file(), "copy missing");
    assert!(
        !store.join("shell/copy.txt").exists(),
        "wrote into /bin view"
    );

    // Without --fs-root there is no writable layer: a mutation is refused by the
    // read-only overlay, in the program's own error vocabulary (an fs error reported as
    // the program's failure outcome, not a missing-capability spawn refusal).
    let denied = eo9(&store, &["-c", "mkdir --path /newdir"]);
    assert_ne!(denied.code, 0, "stdout: {}", denied.stdout);
    assert!(!store.join("shell/newdir").exists(), "wrote into /bin view");
}

#[test]
fn only_strips_the_whole_exec_surface_from_a_restricted_child() {
    // `only` attenuates before spawn: restricting eosh (which requires the full eo9:exec
    // surface) to just text is refused before it runs — proof that the algebra removes
    // exec/compile/spawn, so a locked-down child cannot compose or launch anything.
    let store = temp_store("shell-only-exec");
    let run = eo9(&store, &["shell", "-c", "only eo9:text/text $ eosh"]);
    // The refusal is a compose-time error (printed by eosh), not a run: it never reaches
    // a spawn. It surfaces on stderr and the one-shot reports failure.
    let output = format!("{}{}", run.stdout, run.stderr);
    assert!(
        output.contains("eo9:exec/component-algebra")
            || output.contains("RequiredOutsideAllowList"),
        "only should refuse eosh for lacking the exec surface (code {}): {output}",
        run.code
    );
}

// -----------------------------------------------------------------------------------
// Store, names, describe
// -----------------------------------------------------------------------------------

#[test]
fn store_add_ls_gc_and_run_by_name() {
    let store = temp_store("store-name");
    let hello = component_arg("hello");

    let added = eo9(&store, &["store", "add", &hello, "--name", "hello"]);
    assert_eq!(added.code, 0, "stderr: {}", added.stderr);
    assert!(
        added.stdout.contains("hello -> "),
        "binding missing from output: {}",
        added.stdout
    );

    let listed = eo9(&store, &["store", "ls"]);
    assert_eq!(listed.code, 0, "stderr: {}", listed.stderr);
    assert!(
        listed.stdout.contains("hello "),
        "ls output: {}",
        listed.stdout
    );
    assert!(
        listed.stdout.contains("objects: 1"),
        "ls output: {}",
        listed.stdout
    );

    // Bare dotted names resolve through the store and run exactly like paths.
    let run = eo9(
        &store,
        &["run", "hello", "--name", "store", "--excited", "false"],
    );
    assert_eq!(run.code, 0, "stderr: {}", run.stderr);
    assert!(
        run.stdout.contains("Hello, store."),
        "stdout: {}",
        run.stdout
    );
    assert_eq!(run.stderr.lines().last(), Some("success(greeted)"));

    let unknown = eo9(&store, &["run", "nosuchname"]);
    assert_eq!(unknown.code, 3);
    assert!(
        unknown.stderr.contains("does not resolve"),
        "unexpected error: {}",
        unknown.stderr
    );

    // gc under the default budget keeps everything and reports what it saw.
    let gc = eo9(&store, &["store", "gc"]);
    assert_eq!(gc.code, 0, "stderr: {}", gc.stderr);
    assert!(
        gc.stdout.starts_with("gc: evicted 0"),
        "gc output: {}",
        gc.stdout
    );

    // gc with a zero budget evicts the cache entry the run created.
    let gc_all = eo9(&store, &["store", "gc", "--max-cache-bytes", "0"]);
    assert_eq!(gc_all.code, 0, "stderr: {}", gc_all.stderr);
    assert!(
        gc_all.stdout.starts_with("gc: evicted 1"),
        "gc output: {}",
        gc_all.stdout
    );
}

#[test]
fn describe_shows_kind_imports_and_arguments() {
    let store = temp_store("describe");
    let hello = component_arg("hello");
    let run = eo9(&store, &["describe", &hello]);
    assert_eq!(run.code, 0, "stderr: {}", run.stderr);
    assert!(run.stdout.contains("kind: binary"), "{}", run.stdout);
    assert!(
        run.stdout.contains("eo9:text/text@0.1.0 (required)"),
        "{}",
        run.stdout
    );
    assert!(
        run.stdout.contains("eo9:time/time@0.1.0 (required)"),
        "{}",
        run.stdout
    );
    assert!(run.stdout.contains("--name <string>"), "{}", run.stdout);
    assert!(run.stdout.contains("--excited <bool>"), "{}", run.stdout);
}

#[test]
fn unknown_commands_and_bad_flags_are_usage_errors() {
    let store = temp_store("usage");
    // Not a subcommand, not an option, not a program reference: still a usage error.
    let unknown = eo9(&store, &["--frobnicate"]);
    assert_eq!(unknown.code, 3);
    assert!(unknown.stderr.contains("unknown command"));

    // A name-shaped first argument is an implicit `run` now; an unbound one fails with
    // the resolver's error rather than "unknown command".
    let unbound = eo9(&store, &["no-such-program"]);
    assert_eq!(unbound.code, 3);
    assert!(
        unbound.stderr.contains("does not resolve"),
        "unexpected error: {}",
        unbound.stderr
    );

    let bad_policy = eo9(&store, &["--exec-snapshot", "maybe", "run", "x.wasm"]);
    assert_eq!(bad_policy.code, 3);
    assert!(bad_policy.stderr.contains("clone-or-refuse"));

    let help = eo9(&store, &["help"]);
    assert_eq!(help.code, 0);
    assert!(help.stdout.contains("USAGE"));
    assert!(help.stdout.contains("DEFAULTS"));
}

// -----------------------------------------------------------------------------------
// Demo defaults: bare invocations and first-run seeding
// -----------------------------------------------------------------------------------

#[test]
fn default_invocations_run_the_shell_and_programs() {
    let store = temp_store("demo-defaults");

    // `eo9 -c "<command>"` is the shell's one-shot form; on a fresh store the first
    // start seeds it from the components embedded in the binary.
    let one_shot = eo9(&store, &["-c", "hello --name demo --excited true"]);
    assert_eq!(one_shot.code, 0, "stderr: {}", one_shot.stderr);
    assert!(
        one_shot.stderr.contains("seeded"),
        "first run should seed the store: {}",
        one_shot.stderr
    );
    assert!(
        one_shot.stdout.contains("Hello, demo!"),
        "{}",
        one_shot.stdout
    );
    assert!(
        one_shot.stderr.contains("ok: greeted"),
        "{}",
        one_shot.stderr
    );

    // `eo9 <path> [--flag value …]` is an implicit `run`.
    let hello = component_arg("hello");
    let by_path = eo9(
        &store,
        &[&hello, "--name", "implicit", "--excited", "false"],
    );
    assert_eq!(by_path.code, 0, "stderr: {}", by_path.stderr);
    assert!(
        by_path.stdout.contains("Hello, implicit."),
        "{}",
        by_path.stdout
    );
    assert_eq!(by_path.stderr.lines().last(), Some("success(greeted)"));

    // And so is `eo9 <bare-name> …` once the name is bound (here: by the seeding above).
    let by_name = eo9(&store, &["hello", "--name", "byname", "--excited", "true"]);
    assert_eq!(by_name.code, 0, "stderr: {}", by_name.stderr);
    assert!(
        by_name.stdout.contains("Hello, byname!"),
        "{}",
        by_name.stdout
    );
}

#[test]
fn first_run_seeding_is_idempotent() {
    let store = temp_store("demo-seed");

    let first = eo9(&store, &["-c", "help"]);
    assert_eq!(first.code, 0, "stderr: {}", first.stderr);
    assert!(
        first.stderr.contains("seeded"),
        "first run should seed: {}",
        first.stderr
    );

    let names = |run: &Run| -> Vec<String> {
        run.stdout
            .lines()
            .skip_while(|line| !line.starts_with("names"))
            .take_while(|line| line.starts_with("names") || line.starts_with("  "))
            .map(str::to_owned)
            .collect()
    };
    let listed = eo9(&store, &["store", "ls"]);
    assert_eq!(listed.code, 0);
    let seeded_names = names(&listed);
    for expected in [
        "hello ",
        "eosh ",
        "cruncher ",
        "entropy.seeded ",
        "fs.memfs ",
    ] {
        assert!(
            seeded_names
                .iter()
                .any(|line| line.trim_start().starts_with(expected)),
            "expected {expected:?} among the seeded names: {seeded_names:?}"
        );
    }

    // A second shell start must not reseed or change any binding.
    let second = eo9(&store, &["-c", "help"]);
    assert_eq!(second.code, 0, "stderr: {}", second.stderr);
    assert!(
        !second.stderr.contains("seeded"),
        "second run must not reseed: {}",
        second.stderr
    );
    let relisted = eo9(&store, &["store", "ls"]);
    assert_eq!(names(&relisted), seeded_names);
}

#[test]
fn seeding_never_clobbers_user_bindings() {
    let store = temp_store("demo-seed-user");

    // The user binds `hello` to the cruncher component before ever starting the shell.
    let added = eo9(
        &store,
        &[
            "store",
            "add",
            &component_arg("cruncher"),
            "--name",
            "hello",
        ],
    );
    assert_eq!(added.code, 0, "stderr: {}", added.stderr);

    // The store is no longer empty, so the shell must not seed and `hello` must still be
    // the user's cruncher (its argument signature gives it away).
    let describe = eo9(&store, &["-c", "describe hello"]);
    assert_eq!(describe.code, 0, "stderr: {}", describe.stderr);
    assert!(
        !describe.stderr.contains("seeded"),
        "a non-empty store must not be seeded: {}",
        describe.stderr
    );
    assert!(
        describe.stdout.contains("--seed: u64"),
        "{}",
        describe.stdout
    );
    assert!(
        !describe.stdout.contains("--name: string"),
        "{}",
        describe.stdout
    );

    let listed = eo9(&store, &["store", "ls"]);
    assert!(listed.stdout.contains("names (1):"), "{}", listed.stdout);
}

// -----------------------------------------------------------------------------------
// store reseed and the upgrade refresh of seeded bindings
// -----------------------------------------------------------------------------------

/// `store add <component> --name <name>` and return the object hash it printed.
fn add_as(store: &Path, component: &str, name: &str) -> String {
    let added = eo9(
        store,
        &["store", "add", &component_arg(component), "--name", name],
    );
    assert_eq!(added.code, 0, "stderr: {}", added.stderr);
    added
        .stdout
        .lines()
        .next()
        .expect("store add prints the object hash")
        .trim()
        .to_string()
}

#[test]
fn upgrade_refresh_rebinds_stale_seeded_names() {
    let store = temp_store("reseed-upgrade");

    // First run seeds the store and writes the seed record.
    let first = eo9(&store, &["-c", "help"]);
    assert_eq!(first.code, 0, "stderr: {}", first.stderr);
    assert!(first.stderr.contains("seeded"), "{}", first.stderr);

    // Simulate a store left behind by an *older* eo9: the seeded `hello` points at
    // different bytes (here: the cruncher component) and the recorded fingerprint is not
    // this binary's. The record is rewritten exactly as that older binary would have
    // left it, so `hello` still counts as the seeder's, just out of date.
    let old_hello = add_as(&store, "cruncher", "hello");
    let seed_path = store.join("seed");
    let record = fs::read_to_string(&seed_path).expect("the seed record exists after seeding");
    let rewritten: String = record
        .lines()
        .map(|line| {
            if line.starts_with("fingerprint ") {
                format!("fingerprint {}", "0".repeat(64))
            } else if line.starts_with("hello ") {
                format!("hello {old_hello}")
            } else {
                line.to_string()
            }
        })
        .collect::<Vec<_>>()
        .join("\n")
        + "\n";
    fs::write(&seed_path, rewritten).expect("rewrite the seed record");

    // The next start notices the fingerprint mismatch, refreshes the seeded names, and
    // `hello` greets again instead of failing with cruncher's signature.
    let run = eo9(&store, &["hello", "--name", "upgrade", "--excited", "true"]);
    assert_eq!(run.code, 0, "stderr: {}", run.stderr);
    assert!(
        run.stderr.contains("refreshed") && run.stderr.contains("bundled program"),
        "expected an upgrade-refresh notice: {}",
        run.stderr
    );
    assert!(run.stdout.contains("Hello, upgrade!"), "{}", run.stdout);

    // The refresh is a one-time event: the next run is quiet.
    let again = eo9(&store, &["hello", "--name", "again", "--excited", "false"]);
    assert_eq!(again.code, 0, "stderr: {}", again.stderr);
    assert!(!again.stderr.contains("refreshed"), "{}", again.stderr);
}

#[test]
fn reseed_leaves_user_bindings_alone() {
    let store = temp_store("reseed-user");

    let first = eo9(&store, &["-c", "help"]);
    assert!(first.stderr.contains("seeded"), "{}", first.stderr);

    // The user adds their own name and deliberately re-binds the seeded `cruncher` name
    // to a different component (the hello example).
    let mything = add_as(&store, "cruncher", "mything");
    let overridden_cruncher = add_as(&store, "hello", "cruncher");

    // A forced reseed refreshes only what seeding still owns: both user bindings keep
    // their hashes.
    let reseeded = eo9(&store, &["store", "reseed"]);
    assert_eq!(reseeded.code, 0, "stderr: {}", reseeded.stderr);
    let listed = eo9(&store, &["store", "ls"]);
    assert!(
        listed.stdout.contains(&format!("mything {mything}")),
        "user-added binding must survive a reseed: {}",
        listed.stdout
    );
    assert!(
        listed
            .stdout
            .contains(&format!("cruncher {overridden_cruncher}")),
        "a user-overridden seeded name must survive a reseed: {}",
        listed.stdout
    );
}

#[test]
fn legacy_store_without_a_seed_record_is_refreshed_on_use() {
    let store = temp_store("reseed-legacy-auto");

    let first = eo9(&store, &["-c", "help"]);
    assert!(first.stderr.contains("seeded"), "{}", first.stderr);

    // Make the store look like one seeded by an eo9 from before seed records existed:
    // no record file, and a bundled name holding outdated bytes.
    fs::remove_file(store.join("seed")).expect("remove the seed record");
    add_as(&store, "cruncher", "hello");

    // The store was clearly seeded (eosh is bound), so the next start refreshes the
    // bundled names even without a record, and `hello` is the bundled greeter again.
    let run = eo9(&store, &["hello", "--name", "legacy", "--excited", "false"]);
    assert_eq!(run.code, 0, "stderr: {}", run.stderr);
    assert!(
        run.stderr.contains("refreshed"),
        "expected the legacy refresh notice: {}",
        run.stderr
    );
    assert!(run.stdout.contains("Hello, legacy."), "{}", run.stdout);
}

#[test]
fn store_reseed_recovers_a_legacy_store() {
    let store = temp_store("reseed-legacy-cmd");

    let first = eo9(&store, &["-c", "help"]);
    assert!(first.stderr.contains("seeded"), "{}", first.stderr);

    // A legacy store (no record), with a stale bundled name and a user-added name.
    fs::remove_file(store.join("seed")).expect("remove the seed record");
    add_as(&store, "cruncher", "hello");
    let mything = add_as(&store, "cruncher", "mything");

    // The explicit command refreshes the bundled names (without a record there is no way
    // to tell a re-bound bundled name from a stale one — that is what the user asked
    // for) but never touches names that are not bundled at all.
    let reseeded = eo9(&store, &["store", "reseed"]);
    assert_eq!(reseeded.code, 0, "stderr: {}", reseeded.stderr);
    assert!(
        reseeded.stdout.contains("refreshed"),
        "stdout: {}",
        reseeded.stdout
    );

    let describe = eo9(&store, &["describe", "hello"]);
    assert_eq!(describe.code, 0, "stderr: {}", describe.stderr);
    assert!(
        describe.stdout.contains("--name <string>"),
        "hello must be the bundled greeter again: {}",
        describe.stdout
    );
    let listed = eo9(&store, &["store", "ls"]);
    assert!(
        listed.stdout.contains(&format!("mything {mything}")),
        "user-added binding must survive: {}",
        listed.stdout
    );

    // Running it again reports there is nothing left to do.
    let again = eo9(&store, &["store", "reseed"]);
    assert_eq!(again.code, 0, "stderr: {}", again.stderr);
    assert!(
        again.stdout.contains("already match"),
        "stdout: {}",
        again.stdout
    );
}

// -----------------------------------------------------------------------------------
// coreutils: the basic tool suite (guest/coreutils/*)
// -----------------------------------------------------------------------------------

/// A fresh sandbox directory the shell's children receive as their fs root.
fn temp_sandbox(test: &str) -> PathBuf {
    let dir = Path::new(env!("CARGO_TARGET_TMPDIR")).join(format!("eo9-sandbox-{test}"));
    if dir.exists() {
        fs::remove_dir_all(&dir).expect("failed to clear the sandbox");
    }
    fs::create_dir_all(&dir).expect("failed to create the sandbox");
    dir
}

#[test]
fn coreutils_fs_tools_against_a_sandbox() {
    let store = temp_store("coreutils-fs");
    let sandbox = temp_sandbox("coreutils-fs");
    fs::write(sandbox.join("notes.txt"), "alpha beta\ngamma\n").expect("write fixture");
    let sb = sandbox.to_str().expect("utf-8 sandbox path");

    // ls lists the directory; cat prints contents; wc reports "<lines> <words> <bytes>".
    // Paths are positional (the variadic `paths` tail), through the eosh one-shot.
    let ls = eo9(&store, &["--fs-root", sb, "-c", "ls /"]);
    assert_eq!(ls.code, 0, "stderr: {}", ls.stderr);
    assert!(ls.stdout.contains("notes.txt"), "ls output: {}", ls.stdout);

    let cat = eo9(&store, &["--fs-root", sb, "-c", "cat /notes.txt"]);
    assert_eq!(cat.code, 0, "stderr: {}", cat.stderr);
    assert!(
        cat.stdout.contains("alpha beta"),
        "cat output: {}",
        cat.stdout
    );

    // The named-flag spelling still works: a single value coerces to the one-element list.
    let cat_flag = eo9(&store, &["--fs-root", sb, "-c", "cat --paths /notes.txt"]);
    assert_eq!(cat_flag.code, 0, "stderr: {}", cat_flag.stderr);
    assert!(
        cat_flag.stdout.contains("alpha beta"),
        "cat --paths output: {}",
        cat_flag.stdout
    );

    let wc = eo9(&store, &["--fs-root", sb, "-c", "wc /notes.txt"]);
    assert_eq!(wc.code, 0, "stderr: {}", wc.stderr);
    assert!(wc.stdout.contains("2 3 17"), "wc output: {}", wc.stdout);

    // cp copies a file; the copy appears on the host side of the fs root.
    let cp = eo9(
        &store,
        &["--fs-root", sb, "-c", "cp --src /notes.txt --dst /copy.txt"],
    );
    assert_eq!(cp.code, 0, "stderr: {}", cp.stderr);
    assert!(
        sandbox.join("copy.txt").is_file(),
        "cp did not create copy.txt"
    );
}

#[test]
fn coreutils_take_several_positional_paths() {
    // The variadic tail end to end: `cat a.txt b.txt` prints both files in order, both
    // through the eosh one-shot and through the implicit-run CLI form.
    let store = temp_store("coreutils-variadic");
    let sandbox = temp_sandbox("coreutils-variadic");
    fs::write(sandbox.join("a.txt"), "first\n").expect("write fixture");
    fs::write(sandbox.join("b.txt"), "second\n").expect("write fixture");
    let sb = sandbox.to_str().expect("utf-8 sandbox path");

    let shell_cat = eo9(&store, &["--fs-root", sb, "-c", "cat /a.txt /b.txt"]);
    assert_eq!(shell_cat.code, 0, "stderr: {}", shell_cat.stderr);
    let first = shell_cat.stdout.find("first").expect("first file printed");
    let second = shell_cat
        .stdout
        .find("second")
        .expect("second file printed");
    assert!(first < second, "files out of order: {}", shell_cat.stdout);

    // The same two paths through `eo9 <program> …` directly (positionals at the CLI).
    let _ = eo9(&store, &["-c", "help"]); // seed the store so `cat` resolves by name
    let run_cat = eo9(&store, &["--fs-root", sb, "cat", "/a.txt", "/b.txt"]);
    assert_eq!(run_cat.code, 0, "stderr: {}", run_cat.stderr);
    assert!(
        run_cat.stdout.contains("first") && run_cat.stdout.contains("second"),
        "cat output: {}",
        run_cat.stdout
    );
    assert_eq!(run_cat.stderr.trim(), "success(printed(13))");

    // wc over two files prints a per-file line plus a total.
    let wc = eo9(&store, &["--fs-root", sb, "-c", "wc /a.txt /b.txt"]);
    assert_eq!(wc.code, 0, "stderr: {}", wc.stderr);
    assert!(
        wc.stdout.contains("/a.txt") && wc.stdout.contains("total"),
        "wc output: {}",
        wc.stdout
    );

    // head's earlier parameter is still bound by name while the tail stays positional.
    let head = eo9(
        &store,
        &["--fs-root", sb, "-c", "head --lines 1 /a.txt /b.txt"],
    );
    assert_eq!(head.code, 0, "stderr: {}", head.stderr);
    assert!(
        head.stdout.contains("==> /a.txt <==") && head.stdout.contains("==> /b.txt <=="),
        "head output: {}",
        head.stdout
    );

    // touch + rm accept several paths; the files appear and disappear on the host side.
    let touch = eo9(&store, &["--fs-root", sb, "-c", "touch /x.txt /y.txt"]);
    assert_eq!(touch.code, 0, "stderr: {}", touch.stderr);
    assert!(sandbox.join("x.txt").is_file() && sandbox.join("y.txt").is_file());
    let rm = eo9(&store, &["--fs-root", sb, "-c", "rm /x.txt /y.txt"]);
    assert_eq!(rm.code, 0, "stderr: {}", rm.stderr);
    assert!(!sandbox.join("x.txt").exists() && !sandbox.join("y.txt").exists());
}

#[test]
fn echo_needs_no_filesystem() {
    // echo imports only eo9:text, so it runs with no fs grant at all.
    let store = temp_store("coreutils-echo");
    let run = eo9(&store, &["-c", "echo --text hello-coreutils"]);
    assert_eq!(run.code, 0, "stderr: {}", run.stderr);
    assert!(
        run.stdout.contains("hello-coreutils"),
        "echo output: {}",
        run.stdout
    );
}

#[test]
fn rng_with_seeded_entropy_is_deterministic() {
    let store = temp_store("coreutils-rng");
    let values = |run: &Run| -> Vec<String> {
        run.stdout
            .lines()
            .filter(|line| line.parse::<u64>().is_ok())
            .map(str::to_owned)
            .collect()
    };

    // The same seed yields the same draws across runs (rng imports eo9:entropy, which the
    // composed entropy.seeded provider satisfies and seals).
    let a = eo9(&store, &["-c", "entropy.seeded --seed 43 $ rng --count 3"]);
    let b = eo9(&store, &["-c", "entropy.seeded --seed 43 $ rng --count 3"]);
    assert_eq!(a.code, 0, "stderr: {}", a.stderr);
    assert_eq!(b.code, 0, "stderr: {}", b.stderr);
    let va = values(&a);
    assert_eq!(va.len(), 3, "expected three values: {}", a.stdout);
    assert_eq!(
        va,
        values(&b),
        "seeded rng must be deterministic across runs"
    );

    // A different seed changes the output.
    let c = eo9(&store, &["-c", "entropy.seeded --seed 99 $ rng --count 3"]);
    assert_eq!(c.code, 0, "stderr: {}", c.stderr);
    assert_ne!(values(&c), va, "a different seed must change the draws");
}

#[test]
fn fs_coreutil_without_fs_root_is_refused() {
    // A coreutil that requires eo9:fs is refused before running when no fs is granted.
    let store = temp_store("coreutils-no-fs");
    let _ = eo9(&store, &["-c", "help"]); // seed the store so `cat` resolves by name
    let refused = eo9(&store, &["cat", "/x"]);
    assert_eq!(refused.code, 3, "stderr: {}", refused.stderr);
    assert!(
        refused.stderr.contains("eo9:fs"),
        "expected an fs-capability refusal: {}",
        refused.stderr
    );
}

/// `describe --wiring`: a single reference renders the component as a leaf; several
/// references compose a `$`-chain and render the tree, naming the interposed provider that
/// plain `describe` cannot show (synthesis #7, study 05 #9).
#[test]
fn describe_wiring_renders_a_leaf_and_a_composition_tree() {
    let store = temp_store("describe-wiring");

    // Single reference (a component path): a labelled leaf with its capability surface.
    let hello = component_arg("hello");
    let leaf = eo9(&store, &["describe", "--wiring", &hello]);
    assert_eq!(leaf.code, 0, "stderr: {}", leaf.stderr);
    assert!(leaf.stdout.contains("wiring:"), "stdout: {}", leaf.stdout);
    assert!(leaf.stdout.contains("[binary]"), "stdout: {}", leaf.stdout);
    assert!(
        leaf.stdout.contains("imports:") && leaf.stdout.contains("eo9:text/text"),
        "stdout: {}",
        leaf.stdout
    );

    // Seed the store so bare names resolve, then compose a provider onto a consumer: the
    // tree names the provider (entropy.seeded) that the composed result's surface hides.
    let _ = eo9(&store, &["-c", "help"]);
    let tree = eo9(&store, &["describe", "--wiring", "entropy.seeded", "rng"]);
    assert_eq!(tree.code, 0, "stderr: {}", tree.stderr);
    assert!(tree.stdout.contains("$ compose"), "stdout: {}", tree.stdout);
    assert!(
        tree.stdout.contains("provider: entropy.seeded"),
        "stdout: {}",
        tree.stdout
    );
    assert!(
        tree.stdout.contains("consumer: rng"),
        "stdout: {}",
        tree.stdout
    );
}

// ---------------------------------------------------------------------------------------
// eofs persistence: mkfs.eofs + --disk + fs.eofs (plan/14 milestone 3)
// ---------------------------------------------------------------------------------------

#[test]
fn mkfs_eofs_formats_and_refuses_to_clobber_without_force() {
    let store = temp_store("mkfs");
    let dir = temp_store("mkfs-images");
    let image = dir.join("disk.img");
    let image_arg = image.to_str().expect("utf-8 image path");

    // Creating + formatting a fresh image works and reports the geometry.
    let format = eo9(&store, &["mkfs.eofs", image_arg, "--size", "4M"]);
    assert_eq!(format.code, 0, "stderr: {}", format.stderr);
    assert!(
        format.stdout.contains("formatted"),
        "stdout: {}",
        format.stdout
    );
    assert_eq!(
        fs::metadata(&image).expect("image exists").len(),
        4 * 1024 * 1024
    );

    // A second mkfs without --force refuses: the image now carries an eofs filesystem,
    // and reformatting it silently would be data loss.
    let refuse = eo9(&store, &["mkfs.eofs", image_arg]);
    assert_eq!(refuse.code, 3, "stderr: {}", refuse.stderr);
    assert!(
        refuse.stderr.contains("--force"),
        "stderr: {}",
        refuse.stderr
    );

    // With --force it reformats.
    let force = eo9(&store, &["mkfs.eofs", image_arg, "--force"]);
    assert_eq!(force.code, 0, "stderr: {}", force.stderr);
}

#[test]
fn eofs_keeps_files_across_processes_on_a_disk_image() {
    // The full milestone-3 story: format an image, write through the composed
    // `fs.eofs $ readwrite` chain in one process, then read the data back with
    // `fs.eofs $ cat` in a *new* process. The only state the two runs share is the
    // image file named by --disk.
    let store = temp_store("eofs-persist");
    let dir = temp_store("eofs-persist-images");
    let image = dir.join("disk.img");
    let image_arg = image.to_str().expect("utf-8 image path");

    let format = eo9(&store, &["mkfs.eofs", image_arg, "--size", "8M"]);
    assert_eq!(format.code, 0, "stderr: {}", format.stderr);

    let write = eo9(
        &store,
        &[
            "--disk",
            image_arg,
            "-c",
            "fs.eofs $ readwrite /keep.txt persistent-data",
        ],
    );
    assert_eq!(write.code, 0, "stderr: {}", write.stderr);
    assert!(
        write.stderr.contains("round-tripped(15)"),
        "stderr: {}",
        write.stderr
    );

    // A brand-new process: nothing carries over but the image file itself.
    let read = eo9(
        &store,
        &["--disk", image_arg, "-c", "fs.eofs $ cat /keep.txt"],
    );
    assert_eq!(read.code, 0, "stderr: {}", read.stderr);
    assert!(
        read.stdout.contains("persistent-data"),
        "stdout: {}",
        read.stdout
    );

    let list = eo9(&store, &["--disk", image_arg, "-c", "fs.eofs $ ls /"]);
    assert_eq!(list.code, 0, "stderr: {}", list.stderr);
    assert!(list.stdout.contains("keep.txt"), "stdout: {}", list.stdout);
}

#[test]
fn disk_is_not_granted_without_an_explicit_disk_flag() {
    // Same opt-in posture as the filesystem: without --disk there is no block device at
    // all, and a composed chain that needs one is refused at spawn rather than handed
    // some ambient file.
    let store = temp_store("eofs-no-grant");
    let run = eo9(&store, &["-c", "fs.eofs $ ls /"]);
    assert_ne!(run.code, 0, "stdout: {} stderr: {}", run.stdout, run.stderr);
    let all = format!("{}{}", run.stdout, run.stderr);
    assert!(all.contains("eo9:disk"), "output: {all}");
}

#[test]
fn a_damaged_disk_image_is_a_typed_error_not_a_crash() {
    let store = temp_store("eofs-damaged");
    let dir = temp_store("eofs-damaged-images");
    let image = dir.join("disk.img");
    let image_arg = image.to_str().expect("utf-8 image path");
    let format = eo9(&store, &["mkfs.eofs", image_arg, "--size", "4M"]);
    assert_eq!(format.code, 0, "stderr: {}", format.stderr);

    // Truncate the image behind eofs's back: mounting must surface the program's own
    // typed fs error, not a guest panic or a host crash.
    let file = fs::OpenOptions::new()
        .write(true)
        .open(&image)
        .expect("open image");
    file.set_len(100).expect("truncate image");
    drop(file);

    let run = eo9(&store, &["--disk", image_arg, "-c", "fs.eofs $ ls /"]);
    assert_eq!(run.code, 1, "stdout: {} stderr: {}", run.stdout, run.stderr);
    let all = format!("{}{}", run.stdout, run.stderr);
    assert!(!all.contains("panicked"), "output: {all}");
    assert!(all.contains("error: fs("), "output: {all}");
}
